main/plugins/org.talend.repository.hadoopcluster/META-INF/MANIFEST.MF
main/plugins/org.talend.repository.hdfs/META-INF/MANIFEST.MF
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/action/CreateHDFSSchemaAction.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSFileSelectorForm.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSFileSelectorWizardPage.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSSchemaWizard.java

-- export several packages, add a field and its get method.

TDQ-9605 Profile HDFS files via Hive

---

main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSFileSelectorForm.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSFileSelectorWizardPage.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSSchemaForm.java

-change/add 2 methods from private to protected, to be able to override
by its sub classes.

TDQ-10182 Simplify HDFS file Profiling with Hive - step 2

---

main/plugins/org.talend.hadoop.distribution.cdh500mr2/src/main/java/org/talend/hadoop/distribution/cdh500mr2/CDH500MR2Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh510mr1/src/main/java/org/talend/hadoop/distribution/cdh510mr1/CDH510MR1Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh510mr2/src/main/java/org/talend/hadoop/distribution/cdh510mr2/CDH510MR2Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh540/src/main/java/org/talend/hadoop/distribution/cdh540/CDH540Distribution.java
main/plugins/org.talend.hadoop.distribution.emr240/src/main/java/org/talend/hadoop/distribution/emr240/EMRApache240Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp200/src/main/java/org/talend/hadoop/distribution/hdp200/HDP200Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp210/src/main/java/org/talend/hadoop/distribution/hdp210/HDP210Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp220/src/main/java/org/talend/hadoop/distribution/hdp220/HDP220Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp230/src/main/java/org/talend/hadoop/distribution/hdp230/HDP230Distribution.java
main/plugins/org.talend.hadoop.distribution.piv200/src/main/java/org/talend/hadoop/distribution/piv200/Pivotal200Distribution.java

Have removed the unnecessary codes, Thank your help to merge this PR.

TBD-3343: clean the dead codes

---

main/plugins/org.talend.repository.nosql/src/messages.properties

fix bug of TBD-3348:Cassandra DB version in repository and component are not

TBD-3348:Cassandra DB version in repository and component are not uniform

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/service/HadoopClusterService.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/conf/ClouderaNavigatorOptionPage.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/context/handler/HadoopClusterContextHandler.java
main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/dnd/HCatalogDragAndDropHandler.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/dnd/HDFSDragAndDropHandler.java

TBD-3368:The Cloudera Navigator parameters are not set to component when

---

main/plugins/org.talend.hadoop.distribution.hdp120/src/main/java/org/talend/hadoop/distribution/hdp120/HDP120Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp130/src/main/java/org/talend/hadoop/distribution/hdp130/HDP130Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp200/src/main/java/org/talend/hadoop/distribution/hdp200/HDP200Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp210/src/main/java/org/talend/hadoop/distribution/hdp210/HDP210Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp220/src/main/java/org/talend/hadoop/distribution/hdp220/HDP220Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp230/src/main/java/org/talend/hadoop/distribution/hdp230/HDP230Distribution.java

Hi ,
please review this commit. if it is ok, please merge it to Talend Repository. Thanks!

TDQ-11917 TOS-DQ should support HDP Standalone mode .

---

main/plugins/org.talend.designer.components.bigdata/components/tCassandraConnection/tCassandraConnection_datastax_connect.javajet

https://jira.talendforge.org/browse/TBD-3415

[TBD-3415] tCassandra can't generate code when ssl value is empty

---

main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSSchemaWizard.java

TUP-4534: HDFS&Context:"xmi:id" should not changed after rename

---

main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSSchemaWizard.java

TUP-4534: Restore HDFSSchemaWizard.getTempHDFSConnection() and return

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_main.javajet

https://jira.talendforge.org/browse/TDI-36060

TDI-36060: Unable to insert NULL value to DynamoDB

---

main/plugins/org.talend.hadoop.distribution.hdp120/src/main/java/org/talend/hadoop/distribution/hdp120/HDP120Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp130/src/main/java/org/talend/hadoop/distribution/hdp130/HDP130Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp200/src/main/java/org/talend/hadoop/distribution/hdp200/HDP200Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp210/src/main/java/org/talend/hadoop/distribution/hdp210/HDP210Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp220/src/main/java/org/talend/hadoop/distribution/hdp220/HDP220Distribution.java

please merge it after code review. Thanks

TDQ-11979 don't support Hive1 for some HDP distribution

---

main/features/org.talend.tos.bigdata.libraries.feature/feature.xml

https://jira.talendforge.org/browse/TDI-36220

TDI-36220: remove the redshift jar from bd plugins

---

main/plugins/org.talend.repository.hadoopcluster/src/messages.properties

TBD-3437:Word "Cloudera" is spelled as "Clouder" wrongly in the cloudera

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/conf/ClouderaNavigatorOptionPage.java

TBD-3727 fix: No bounding box  for password filed in Cloudera Navigator wizard
https://jira.talendforge.org/browse/TBD-3727

TBD-3727 fix: No bounding box  for password filed in Cloudera Navigator

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java

Whether or not selecting "Force MapR Ticket Authenticate", the username and group filed must be enabled.

TBD-3697:Custom UserGroup enabled username and group filed.

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/common/cassandra/ICassandraConstants.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/cassandra/CassandraConnForm.java

Cassandra 3.0: Need remove API type dropdownlist should be consistent with component
https://jira.talendforge.org/browse/TBD-3367

TBD-3367 fix:Cassandra 3.0: Need remove API type dropdownlist should be

---

main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/model/HDFSConnectionBean.java
main/plugins/org.talend.repository.hadoopcluster/plugin.xml
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/migration/ReviseInvalidContextNamesOfHadoopPropertiesMigrationTask.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/util/HDFSModelUtil.java

TUP-5009: [6.1.1] Export Context on Metadata Hadoop Connection erroneous

---

main/plugins/org.talend.repository.nosql/src/messages.properties

old version
https://jira.talendforge.org/browse/TBD-3821

TBD-3821 fix:DB Version for neo4j 2.3.x should be coordinate with the

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/MetadataHadoopClusterContentProvider.java

https://jira.talendforge.org/browse/TUP-5164

TUP-5164 fix> GIT: CopyToBranch doesn't work

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/common/AbstractNoSQLRetrieveSchemaForm.java

the list
https://jira.talendforge.org/browse/TBD-3953

TBD-3953 fix: Mongodb: next button disable if unselect any table from

---

main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/HCatalogSchemaWizard.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSSchemaWizard.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/wizards/NoSQLSchemaWizard.java

TDI-37120: Edit schema which used in job, will hang on "Progress

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/MetadataHadoopClusterContentProvider.java

https://jira.talendforge.org/browse/TBD-3985

TBD-3985 fix: Hadoop cluster item is not shown after created for local project

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/util/HCRepositoryUtil.java

https://jira.talendforge.org/browse/TBD-4018

TBD-4018 fix: hcatalog item will broken when click finish button for existing hcatalog

---

main/plugins/org.talend.repository.hbaseprovider/src/org/talend/repository/hbaseprovider/provider/HBaseMetadataProvider.java

zookeeper node parent on wizard
https://jira.talendforge.org/browse/TUP-15970

TUP-15970 fix: Hbase:Cann't check successfully when I check set

---

main/plugins/org.talend.hadoop.distribution.hdp240/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdp250/plugin.xml
test/plugins/org.talend.hadoop.distribution.hdp240.test/src/org/talend/hadoop/distribution/hdp240/test/HDP240ClassLoaderTest.java
test/plugins/org.talend.hadoop.distribution.hdp250.test/src/org/talend/hadoop/distribution/hdp250/test/HDP250ClassLoaderTest.java

https://jira.talendforge.org/browse/TUP-16005

TUP-16005 fix: Cann't retrieve schema for AVRO file with HDP 25

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/context/handler/HadoopClusterContextHandler.java

has exported as context to tHDFSInput.

TUP-16064: Compile error when import a MapR 52 Ticket hdfs item which

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/action/common/CreateHadoopNodeAction.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hbase/action/CreateHBaseAction.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hive/action/CreateHiveAction.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/maprdb/action/CreateMaprdbAction.java

when hadoop cluster is on context mode.

TUP-16056: HDP 25 kerberos:Hive,Hbase context cann't check successfully

---

main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/hadoop/service/check/AbstractCheckedServiceProvider.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/hadoop/service/check/provider/CheckedJobtrackerProvider.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/hadoop/service/check/provider/CheckedNamenodeProvider.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/hadoop/service/check/provider/CheckedResourceManagerProvider.java

https://jira.talendforge.org/browse/TUP-15473
this pull request is based on https://github.com/Talend/tcommon-studio-se/pull/698

TUP-15473 fix: Namenode cannot check successfully when checking it for the first time which using CDH 57 Kerberos HA

---

main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/controllers/AbstractHDFSBrowseController.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/manager/HadoopClassLoaderFactory.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/service/HadoopClusterService.java

TUP-16076 fix:HDFS file browser is not open when using hdfs component on

---

main/plugins/org.talend.hadoop.distribution.mapr510/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr520/plugin.xml

https://jira.talendforge.org/browse/TUP-15582

TUP-15582 fix: MapR 51 HBase cannot check successfully on Windows 8.1

---

main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/controllers/AbstractHDFSBrowseController.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/manager/EHadoopParameter.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/manager/HadoopServerUtil.java

button after "File Name" for MapR 5.1

TUP-15310 fix: HDFS Browse does not open successfully when clicking

---

i18n/plugins/org.talend.designer.hdfsbrowse.nl/src/messages_fr.properties

TUP-16178 fix:Unable to click the "Error log" button in the Hadoop

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/handler/cassandra/CassandraMetadataHandler.java

when another port is used than 9042

TUP-15874 fix:The Cassandra Connection Wizard does not retrieve schemas

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/context/NoSQLConnectionContextManager.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/mongodb/MongoDBConnForm.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/service/NOSQLService.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/context/handler/NoSQLRepositoryContextHandler.java
test/plugins/org.talend.repository.nosql.test/src/org/talend/repository/nosql/context/NoSQLConnectionContextManagerTest.java
test/plugins/org.talend.repository.nosql.test/src/org/talend/repository/nosql/service/NOSQLServiceTest.java
test/plugins/org.talend.repository.nosql.test/src/org/talend/repository/nosql/ui/context/handler/NoSQLRepositoryContextHandlerTest.java

TUP-15459: Mongodb replica set: when convert it to context,replica

---

main/plugins/org.talend.designer.pigmap/src/main/java/org/talend/designer/pigmap/model/emf/pigmap/impl/ConnectionImpl.java

parts, one is deactivated, the other is activated

TUP-5635：cann't generate jobscript when job has two tPigLoad->tPigMap

---

main/features/org.talend.rcp.branding.tos.bigdata.feature/feature.xml

Reverts Talend/tbd-studio-se#169

Revert "TMDM-10190: remove mdm webservice ce plugin from feature list."

---

main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/hadoop/service/check/CheckHadoopServicesDialog.java

bugfix: TUP-16644 Maximize button is disabled on shell "Checking Hadoop

---

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml
main/plugins/org.talend.repository.nosql/src/messages.properties
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/common/neo4j/INeo4jAttributes.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/common/neo4j/INeo4jConstants.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/neo4j/Neo4jDNDProvider.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/neo4j/Neo4jConnForm.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/neo4j/Neo4jConnectionUtil.java
test/plugins/org.talend.repository.nosql.test/src/org/talend/repository/nosql/db/util/neo4j/Neo4jConnectionUtilTest.java

1. Add "Set username" parameter in metadata connection and link to related components.
2. Fix some UI problems.
3. Refactor and improve some codes.

TUP-15491: On the edit Neo4j 2.1.x connection wizard has username and password field

---

main/plugins/org.talend.hadoop.distribution/resources/config/default/mapr.json
test/plugins/org.talend.hadoop.distribution.mapr200.test/src/org/talend/hadoop/distribution/mapr200/test/MapR200DefaultConfigurationTest.java
test/plugins/org.talend.hadoop.distribution.mapr212.test/src/org/talend/hadoop/distribution/mapr212/test/MapR212DefaultConfigurationTest.java
test/plugins/org.talend.hadoop.distribution.mapr213.test/src/org/talend/hadoop/distribution/mapr213/test/MapR213DefaultConfigurationTest.java
test/plugins/org.talend.hadoop.distribution.mapr301.test/src/org/talend/hadoop/distribution/mapr301/test/MapR301DefaultConfigurationTest.java
test/plugins/org.talend.hadoop.distribution.mapr310.test/src/org/talend/hadoop/distribution/mapr310/test/MapR310DefaultConfigurationTest.java
test/plugins/org.talend.hadoop.distribution.mapr401.test/src/org/talend/hadoop/distribution/mapr401/test/MapR401DefaultConfigurationTest.java
test/plugins/org.talend.hadoop.distribution.mapr410.test/src/org/talend/hadoop/distribution/mapr410/test/MapR410DefaultConfigurationTest.java
test/plugins/org.talend.hadoop.distribution.mapr500.test/src/org/talend/hadoop/distribution/mapr500/test/MapR500DefaultConfigurationTest.java
test/plugins/org.talend.hadoop.distribution.mapr510.test/src/org/talend/hadoop/distribution/mapr510/test/MapR510DefaultConfigurationTest.java
test/plugins/org.talend.hadoop.distribution.mapr520.test/src/org/talend/hadoop/distribution/mapr520/test/MapR520DefaultConfigurationTest.java

bugfix: TUP-15590 MapR Namenode URI default value is not same as the

---

main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/dnd/HCatalogDragAndDropHandler.java

and staging directory are not set automatically when importing
repository hcatalog item to tPigLoad

bugfix: TUP-15675 Jobhistory address, resourcemanager scheduler address

---

main/plugins/org.talend.hadoop.distribution.emr500/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr500/src/main/java/org/talend/hadoop/distribution/emr500/EMR500Distribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/spark/SparkClassPathUtils.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/utils/ModuleGroupsUtils.java

- Add Spark 2 helper utilities to the distributions API
- Update EMR5.0.0 Spark 2 support
Goes with : https://github.com/Talend/tbd-studio-ee/pull/80
**NB :** Once the PR is reviewed and merged the maintenance/6.3 branch should be merged with master to allow Dev/QA to test the fix

support Spark 2 in the distributions API

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/service/HadoopClusterService.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/util/HCRepositoryUtil.java

TUP-17186:Reference project does not add the hadoop-conf-connection.jar

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/6.1.1-TPS-1301_TPS-1310]

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/6.1.1-TPS-1301]

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/6.1.1-TPS-1310]

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/6.1.1-TPS-1779]

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/6.1.1]

---

.github/PULL_REQUEST_TEMPLATE.md

chore(project) : add PR template

---

main/plugins/org.talend.hadoop.distribution.hdp240/src/main/java/org/talend/hadoop/distribution/hdp240/modulegroup/HDP240HiveOnSparkModuleGroup.java

Missing TEZ libraries from HDP distribution when used with Spark
Add TEZ libraries

fix(TBD-4677) : add TEZ module group to Hive on Spark

---

main/plugins/org.talend.hadoop.distribution.hdp240/src/main/java/org/talend/hadoop/distribution/hdp240/modulegroup/HDP240HiveOnSparkModuleGroup.java
main/plugins/org.talend.hadoop.distribution.hdp250/src/org/talend/hadoop/distribution/hdp250/modulegroup/HDP250HiveOnSparkModuleGroup.java
test/plugins/org.talend.hadoop.distribution.hdp250.test/src/org/talend/hadoop/distribution/hdp250/test/modulegroup/HDP250HiveOnSparkModuleGroupTest.java

cherry-picked TUP commits prevented a clean merge between maintenance/6.3 and master
Resolve conflicts

merge(TBD-4677) : merge and resolve maintenance branches

---

main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml

Update launcher version to add custom log level support

TBD4720 Update launcher version

---

main/plugins/org.talend.hadoop.distribution.cdh580spark2/src/main/java/org/talend/hadoop/distribution/cdh580spark2/CDH580Spark2Distribution.java
test/plugins/org.talend.hadoop.distribution.cdh580spark2.test/src/org/talend/hadoop/distribution/cdh580spark2/test/CDH580Spark2DistributionTest.java

Standalone mode available on cdh58 spark 2
Standalone mode not available on cdh58 spark 2

fix(TBD-4737): Fix standalone mode on cdh58 spark 2

---

test/plugins/org.talend.hadoop.distribution.dataproc11.test/src/org/talend/hadoop/distribution/dataproc11/test/modulegroup/Dataproc11SparkStreamingModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.hdp240.test/src/org/talend/hadoop/distribution/hdp240/test/modulegroup/HDP240HiveOnSparkModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/condition/ComponentConditionUtilTest.java

Failing Junit Bigdata tests : http://192.168.31.21:8080/view/Junits_Studio/job/Studio_JUnit_master_DI/lastCompletedBuild/testReport/
Fix failing Junit tests

fix(tests) : fix failing junit tests

---

main/plugins/org.talend.hadoop.distribution/resources/config/default/google_cloud_dataproc.json
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/GoogleDataprocInfoForm.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/util/HCRepositoryUtil.java

Missing default value on Google Cloud Dataproc wizard
Add default value on Google Cloud Dataproc wizard

fix TUP-17438:Add default value on Google Cloud Dataproc wizard

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/conf/AbstractConnectionForm.java

https://jira.talendforge.org/browse/TUP-17458

fix(TUP-17458): Cann't retrieve from Ambari or Clouder manager on TOS BD

---

main/plugins/org.talend.repository.hadoopcluster.configurator/src/org/talend/repository/hadoopcluster/configurator/RetrieveConfigurationProcess.java

TUP-17474 BD metadata (cluster config, Hive etc.) through job server, one file's content is error
https://jira.talendforge.org/browse/TUP-17474
https://jira.talendforge.org/browse/TUP-17474

fix(TUP-17474): BD metadata (cluster config, Hive etc.) through job server, one file's content is error

---

main/plugins/org.talend.hadoop.distribution.cdh580/src/main/java/org/talend/hadoop/distribution/cdh580/CDH580Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh580spark2/src/main/java/org/talend/hadoop/distribution/cdh580spark2/CDH580Spark2Distribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/HadoopComponent.java
main/plugins/org.talend.repository.oozie/META-INF/MANIFEST.MF
main/plugins/org.talend.repository.oozie/src/org/talend/repository/oozie/action/CreateOozieAction.java

Context menu "Create Oozie" should not show on Cloudera Spark 2 Hadoop
Cluster
https://jira.talendforge.org/browse/TUP-17371

bugfix TUP-17371

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/DistributionHelperTest.java

Context menu "Create Oozie" should not show on Cloudera Spark 2 Hadoop
Cluster
junit changed
https://jira.talendforge.org/browse/TUP-17371

bugfix-TUP-17371

---

main/plugins/org.talend.hadoop.distribution.cdh580spark2/plugin.xml

Spark streaming - Kafka needed HDFS configuration
Spark streaming job with Kafka components run without HDFS component

fix(TBD-4743) fix missing HDFS jars

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/ESparkVersion.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/spark/SparkVersionUtil.java

feat(spark 2.1): Support for Spark 2.1 in the distribution API

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/conf/HadoopImportRemoteOptionPage.java

https://jira.talendforge.org/browse/TUP-17529

fix(TUP-17529):Can't_retrieve_configuration_from_Cloudera_Manager

---

main/plugins/org.talend.designer.components.bigdata/components/tELTHiveOutput/tELTHiveOutput_main.javajet

Missed fixes from comments on from PR https://github.com/Talend/tbd-studio-se/pull/291

fix(TBD-4722): Add logs for Hive on Dataproc.

---

main/plugins/org.talend.hadoop.distribution.emr550/plugin.xml

fix(tbd-4936): Homogenize netty-all dependency for EMR 5.5.0

---

pom.xml
test/features/org.talend.bigdata.se.test.feature/feature.xml

chore(build): Remove inexisting plugin from the pom aggregator

---

main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml

[TBD-4722] Fix jar path.

---

main/plugins/org.talend.repository.oozie/src/messages.properties
main/plugins/org.talend.repository.oozie/src/org/talend/repository/oozie/ui/AbstractOozieForm.java

https://jira.talendforge.org/browse/TUP-15184

bugfix(TUP-15184)Wrong info shows when check Oozie connection fails

---

main/plugins/org.talend.hadoop.distribution/resources/config/default/microsoft_hd_insight.json
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/HDIInfoForm.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/util/HCRepositoryUtil.java

-added fillDefaults method for HDIInfoForm
-added parameters for HDInsight default value
-added a default json for HDInsight
https://jira.talendforge.org/browse/TUP-17592

bugfix(TUP-17592)No default value for HDInsight hadoop wizard

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/HDIInfoForm.java

https://jira.talendforge.org/browse/TUP-17575

bugfix(TUP-17575)Remove "Job result folder" from HDI wizard

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java

fix(TUP-17589): NoClassFoundException for Resource Manager when hadoop is created as Custom

---

main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml

fix(TBD-4972): Upgrade bigdata-launcher version.

---

main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml

fix(TBD-4972): use correct timestamp.

---

main/plugins/org.talend.designer.pigmap/src/main/java/org/talend/designer/pigmap/model/emf/pigmap/IConnection.java
main/plugins/org.talend.designer.pigmap/src/main/java/org/talend/designer/pigmap/model/emf/pigmap/impl/AbstractInOutTableImpl.java
main/plugins/org.talend.designer.pigmap/src/main/java/org/talend/designer/pigmap/model/emf/pigmap/impl/AbstractNodeImpl.java
main/plugins/org.talend.designer.pigmap/src/main/java/org/talend/designer/pigmap/model/emf/pigmap/impl/InputTableImpl.java
main/plugins/org.talend.designer.pigmap/src/main/java/org/talend/designer/pigmap/model/emf/pigmap/impl/OutputTableImpl.java
main/plugins/org.talend.designer.pigmap/src/main/java/org/talend/designer/pigmap/model/emf/pigmap/impl/PigMapDataImpl.java
main/plugins/org.talend.designer.pigmap/src/main/java/org/talend/designer/pigmap/model/emf/pigmap/impl/TableNodeImpl.java
main/plugins/org.talend.designer.pigmap/src/main/java/org/talend/designer/pigmap/model/emf/pigmap/impl/VarTableImpl.java
pom.xml
test/features/org.talend.bigdata.se.test.feature/feature.xml
test/plugins/org.talend.designer.pigmap.test/.classpath
test/plugins/org.talend.designer.pigmap.test/.project
test/plugins/org.talend.designer.pigmap.test/META-INF/MANIFEST.MF
test/plugins/org.talend.designer.pigmap.test/build.properties
test/plugins/org.talend.designer.pigmap.test/pom.xml
test/plugins/org.talend.designer.pigmap.test/src/org/talend/designer/pigmap/model/emf/pigmap/impl/PigMapDataImplTest.java

not get saved
joblet update does not work well
joblet update does work well

fix(TUP-17556):Changes to a tmap in an expanded joblet from a job does

---

main/plugins/org.talend.hadoop.distribution.dataproc11/OSGI-INF/dataproc11.xml
main/plugins/org.talend.hadoop.distribution.dataproc11/src/main/java/org/talend/hadoop/distribution/dataproc11/Dataproc11Distribution.java

MR doesn't support the submitting Dataproc jobs
Implement the required interfaces to support MR jobs in dataproc

feat(TBD-4939) : support MR jobs with dataproc

---

main/plugins/org.talend.hadoop.distribution/resources/config/default/microsoft_hd_insight.json
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/HDIInfoForm.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/util/HCRepositoryUtil.java
test/plugins/org.talend.repository.hadoopcluster.test/src/main/java/org/talend/repository/hadoopcluster/testutils/HCRepositoryUtilTest.java

https://jira.talendforge.org/browse/TUP-17771

fix(TUP-17771):Should not remove "Job result folder" from HDI wizard

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/neo4j/Neo4jMetadataProvider.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/neo4j/Neo4jConnectionUtil.java
test/plugins/org.talend.repository.nosql.test/src/org/talend/repository/nosql/db/util/neo4j/Neo4jConnectionUtilTest.java
test/plugins/org.talend.repository.nosql.test/src/org/talend/repository/nosql/db/util/neo4j/Neo4jMetadataProviderTest.java

*close db connection after check connection.
*clean cache for extractTheColumns(), which is retrieving schema.
https://jira.talendforge.org/browse/TUP-15696

bugfix(TUP-15696)Neo4j check connection success or fail have error.

---

main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/manager/HadoopServerUtil.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/model/EHadoopAdditionalJars.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/model/EHadoopAdditionalJarsMapping.java

not add the needed jars automatically maybe for any distribution if the lzo property is setup
to add the needed jars automatically maybe for any distribution if the lzo property is setup

TUP-17114:Cann't retrieve schma for HDFS when studio is on EC2 instance when EC2 and EMR5 are in same VPC

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml

fix(cdh5100): Fix the artifact ID of a Spark 2 dependency

---

main/plugins/org.talend.designer.hdfsbrowse/META-INF/MANIFEST.MF
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/constants/HadoopPatternConstants.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/common/HadoopPropertiesWizardPage.java
main/plugins/org.talend.repository.hdfs/plugin.xml

https://jira.talendforge.org/browse/TUP-17829

fix(TUP-17829):incorrect characters can be saved when edit property

---

main/plugins/org.talend.hadoop.distribution.emr103/src/main/java/org/talend/hadoop/distribution/emr103/EMRApache103Distribution.java
main/plugins/org.talend.hadoop.distribution.emr450/src/main/java/org/talend/hadoop/distribution/emr460/EMR460Distribution.java

https://jira.talendforge.org/browse/TUP-17659

fix(TUP-17659)EMR 55 hbase should not enable kerberos authentication

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/neo4j/Neo4jConnForm.java

https://jira.talendforge.org/browse/TUP-15696

fix(TUP-15696)neo4j check connection with blank path

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/GoogleDataprocInfoForm.java

Not add Hadoop Proerty setting on Google Dataproc wizard since it has not support MR.
Add Hadoop Proerty setting on Google Dataproc wizard for it has supported MR now

feat TUP-17854:Add Hadoop Proerty setting on Google Dataproc wizard for it has supported MR now

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/HDIInfoForm.java

On create HDInsight wizard don't have hadoop properties
Add hadoop properties on create HDInsight wizard.

feat TUP-17774:On create HDInsight wizard don't have hadoop properties

---

main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml

Compile error and ClassNotFoundException.
No compile error and ClassNotFoundException.

fix(TBD-5116): Add guava and commons-collections jars for hdinsight360

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/utils/ComponentConditionUtil.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/condition/ComponentConditionUtilTest.java

fix: junit failed

---

main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/creator/HDFSConnectionCreator.java

*retrieve username according to context type
https://jira.talendforge.org/browse/TUP-17908

fix(TUP-17908)doublequotes are added to the username context variable

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/conf/HadoopConfsUtils.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/service/HadoopClusterService.java
test/plugins/org.talend.repository.hadoopcluster.test/src/main/java/org/talend/repository/hadoopcluster/conf/HadoopConfsUtilsTest.java

hadoop-conf-name.jar to browser

fix(TUP-17664): change context group name,then run job will pop up

---

main/plugins/org.talend.hadoop.distribution.altus10/plugin.xml

This reverts commit fd04c581ca443f61ede3adb619c5d20d6752ae69.
tKinesisInput can't work with current dependencies
Correct dependencies for tKinesisInput

Revert "feat(TBD-5053): Fix dependencies for Kinesis Output."

---

main/plugins/org.talend.hadoop.distribution.altus10/.classpath

Altus classpath is not correct
correct it after source path changed

fix(TBD-5196): correct Altus plugin classpath

---

main/plugins/org.talend.hadoop.distribution.cdh580spark2/plugin.xml

NoClassDefFoundError exception occurred when using tFileInputParquet and tFileOutputParquet with CDH5.8 Spark2.
No exception occured when using tFileInputParquet and tFileOutputParquet with CDH5.8 Spark2.

fix(TBD-4896): fix the version of parquet dependencies

---

test/plugins/org.talend.hadoop.distribution.cdh5100.test/src/org/talend/hadoop/distribution/cdh5100/test/modulegroup/CDH5100SparkBatchModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.cdh5100.test/src/org/talend/hadoop/distribution/cdh5100/test/modulegroup/CDH5100SparkStreamingModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.emr550.test/src/org/talend/hadoop/distribution/emr550/test/EMR550DistributionTest.java

Some bd junits failed since the new modification.
Enhance and fix some bd failed junits.

fix TUP-17687:Enhance and fix some bd failed junits.

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

https://jira.talendforge.org/browse/TDI-38852

fix(TDI-38852): Align apache http versions

---

i18n/plugins/org.talend.designer.hdfsbrowse.nl/src/messages_en.properties
i18n/plugins/org.talend.designer.hdfsbrowse.nl/src/messages_fr.properties
main/plugins/org.talend.designer.hdfsbrowse/src/messages.properties
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/hadoop/service/check/CheckHadoopServicesDialog.java

https://jira.talendforge.org/browse/TUP-17828

fix(TUP-17828)No link to error logs when check services in hc

---

main/plugins/org.talend.hadoop.distribution.hdp120/src/main/java/org/talend/hadoop/distribution/hdp120/HDP120Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp130/src/main/java/org/talend/hadoop/distribution/hdp130/HDP130Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp200/src/main/java/org/talend/hadoop/distribution/hdp200/HDP200Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp210/src/main/java/org/talend/hadoop/distribution/hdp210/HDP210Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp220/src/main/java/org/talend/hadoop/distribution/hdp220/HDP220Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp230/src/main/java/org/talend/hadoop/distribution/hdp230/HDP230Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp240/src/main/java/org/talend/hadoop/distribution/hdp240/HDP240Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp250/src/org/talend/hadoop/distribution/hdp250/HDP250Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp260/src/org/talend/hadoop/distribution/hdp260/HDP260Distribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/HadoopComponent.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/conf/AbstractHadoopImportConfsPage.java

HDP specific properties (Hive hooks, ...) are not filtered which cause some jobs to fail 
Filter these properties.
Documentation : https://jira.talendforge.org/browse/TBD-4593

feat(TBD-4455) : add HDP specific fixes

---

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml

fix(hdp260): Review the dependencies maven path

---

main/plugins/org.talend.hadoop.distribution.emr500/plugin.xml
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/model/DistributionVersion.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/conf/AbstractHadoopImportConfsPage.java

The merge from `maintenance/6.3` could not be done without conflicts since the TUP team always use cherry-picks between branches.
This PR is the result of the command `git merge -X ours origin/maintenance/6.3` to keep `master` contents on all conflicting files.

fix(TBD-4617): merge changes from maintenance/6.3

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/model/DistributionVersion.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/conf/AbstractHadoopImportConfsPage.java

https://jira.talendforge.org/browse/TUP-17316
Just fix a compile error

fix(TUP-17316)Fix a compile error

---

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdp260/src/org/talend/hadoop/distribution/hdp260/modulegroup/HDP260HiveOnSparkModuleGroup.java

- Test on Spark version is working
- No more several versions of commons-lang

TBD-4991 HDP260 Fix Hive on Spark dependencies

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/neo4j/Neo4jConnForm.java

https://jira.talendforge.org/browse/TUP-17997

fix(TUP-17997)Check button is still disable when create neo4j connection

---

main/plugins/org.talend.hadoop.distribution.altus10/META-INF/MANIFEST.MF

https://jira.talendforge.org/browse/TUP-17988

fix(TUP-17988)Hide Altus from distributions available on the wizard

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/dnd/HadoopClusterDragAndDropHandler.java
main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/dnd/HCatalogDragAndDropHandler.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/dnd/HDFSDragAndDropHandler.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/dnd/NoSQLDragAndDropHandler.java

fix(TUP-17983): random issue when logon remote project error pop up
https://jira.talendforge.org/browse/TUP-17983

fix(TUP-17983): random issue when logon remote project error pop up

---

main/plugins/org.talend.hadoop.distribution.altus10/META-INF/MANIFEST.MF

Reverts Talend/tbd-studio-se#360

Revert "fix(TUP-17988)Hide Altus from distributions available on the wizard"

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/helper/DistributionsManager.java

https://jira.talendforge.org/browse/TUP-17988

fix(TUP-17988)Hide Cloudera altus from distributions on the wizard

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_begin.javajet

**What is the current behavior?**
https://jira.talendforge.org/browse/TDI-38904

fix(TDI-38904): Tracking influence for AWS connectors

---

main/plugins/org.talend.designer.hdfsbrowse/META-INF/MANIFEST.MF
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/controllers/AbstractHDFSBrowseController.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/manager/HadoopServerUtil.java

Show error logs.
Show a message about unsupport action for Google Dataproc.

fix(TBD-5130): Update browse folder action in component support HDFS for Google Dataproc MR

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_begin.javajet

**What is the current behavior?**
https://jira.talendforge.org/browse/TDI-38904

fix(TDI-38904): change the value for user agent

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml

fix(TBD-5078): Use the right avro-mapred version in the Spark 2 group for CDH 5.10

---

main/plugins/org.talend.hadoop.distribution.cdh580spark2/plugin.xml

ClassNotFoundException error occured when running DynamoDB. HttpClient library is missing.
No ClassNotFoundException error occured when running DynamoDB. Add HttpClient library for CDH580 Spark2.0.

fix(TBD-4880): Add httpclient library for CDH580 Spark2.0

---

test/plugins/org.talend.hadoop.distribution.test.base/src/main/java/org/talend/hadoop/distribution/test/TestUtils.java
test/plugins/org.talend.hadoop.distribution.test.base/src/main/java/org/talend/hadoop/distribution/test/hive/AbstractDistributionTest4HiveMetadataHelper.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/HadoopDistributionsHelperTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/ImpalaDistributionsTest.java

test(TUP-17636): fix some failed junits.

---

main/plugins/org.talend.designer.components.bigdata/components/tELTHiveMap/tELTHiveMap_main.javajet

https://jira.talendforge.org/browse/TDI-39029

fix(TDI-38946): When Deploying one customer's job in CI, the build failed  with error: constant string too long

---

main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml

fix(TBD-5301): Add missing dependencies to the Spark group

---

main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml
main/plugins/org.talend.hadoop.distribution.dataproc11/src/main/java/org/talend/hadoop/distribution/dataproc11/Dataproc11Distribution.java
main/plugins/org.talend.hadoop.distribution.dataproc11/src/main/java/org/talend/hadoop/distribution/dataproc11/modulegroup/node/sparkbatch/Dataproc11SparkBatchGraphFramesNodeModuleGroup.java

feat(TDQ-13839/TDQ-13986): graphframe for dataproc11

---

main/plugins/org.talend.repository.hbaseprovider/src/org/talend/repository/hbaseprovider/provider/HBaseMetadataProvider.java
main/plugins/org.talend.repository.maprdbprovider/src/main/java/org/talend/repository/maprdbprovider/provider/MapRDBMetadataProvider.java

Not support limit rows for MapRDB / hbase etc
Support limit rows

TUP-18046:Cannot Retrieve Columns from Metadata MapRDB Database Connection.

---

main/plugins/org.talend.repository.hbaseprovider/src/org/talend/repository/hbaseprovider/provider/HBaseMetadataProvider.java
main/plugins/org.talend.repository.maprdbprovider/src/main/java/org/talend/repository/maprdbprovider/provider/MapRDBMetadataProvider.java

Connection.
Not support limit rows for MapRDB / hbase etc
Support limit rows

TUP-18046:Cannot Retrieve Columns from Metadata MapRDB Database

---

test/plugins/org.talend.hadoop.distribution.hdp260.test/src/org/talend/hadoop/distribution/hdp260/test/modulegroup/HDP260SparkBatchModuleGroupTest.java
test/plugins/org.talend.repository.hadoopcluster.test/src/main/java/org/talend/repository/hadoopcluster/service/HadoopClusterServiceTest.java

test(TUP-18151): fix junits

---

main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/HCatalogWizard.java

https://jira.talendforge.org/browse/TUP-18169

fix(TUP-18169)fail to parse port for Hcatalog from context variables

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/conf/HadoopConfsUtils.java

https://jira.talendforge.org/browse/TUP-17904

fix(TUP-17904):Export Context with multiple groups is slow

---

main/plugins/org.talend.repository.hbaseprovider/src/org/talend/repository/hbaseprovider/provider/HBaseMetadataProvider.java
main/plugins/org.talend.repository.maprdbprovider/src/main/java/org/talend/repository/maprdbprovider/provider/MapRDBMetadataProvider.java

What is the current behavior? (You can also link to an open issue here)
Not support limit rows for MapRDB / hbase etc
What is the new behavior?
Support limit rows

TUP-18046:refix of Cannot Retrieve Columns from Metadata MapRDBDatabase.

---

main/plugins/org.talend.repository.hbaseprovider/src/org/talend/repository/hbaseprovider/provider/HBaseMetadataProvider.java
main/plugins/org.talend.repository.maprdbprovider/src/main/java/org/talend/repository/maprdbprovider/provider/MapRDBMetadataProvider.java

What is the current behavior? (You can also link to an open issue here)
Not support limit rows for MapRDB / hbase etc
What is the new behavior?
Support limit rows

TUP-18046:refix of cannot Retrieve Columns for maprdb/hbase.

---

main/plugins/org.talend.designer.hdfsbrowse/src/messages.properties
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/controllers/AbstractHDFSBrowseController.java

https://jira.talendforge.org/browse/TUP-17955

fix(TUP-17955)Unclear error message when select input file in tHMapFile

---

test/plugins/org.talend.repository.hadoopcluster.test/META-INF/MANIFEST.MF
test/plugins/org.talend.repository.hadoopcluster.test/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeRepositoryValueFromCdhtoEmrTest.java

https://jira.talendforge.org/browse/TUP-17721

fix(TUP-17721)Username in SparkConfiguation is missing

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/viewer/HadoopSubMultiRepTypeProcessor.java

Reverts Talend/tbd-studio-se#418

Revert "fix(TUP-17378)Should not show CDH 5.8 Spark 2 distribution in MR job"

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/viewer/HadoopSubMultiRepTypeProcessor.java

https://jira.talendforge.org/browse/TUP-17378

fix(TUP-17378)Should not show CDH 5.8 Spark 2 distribution in MR job

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_main.javajet

https://jira.talendforge.org/browse/TDI-39056?focusedCommentId=491441&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-491441
Make sortKey optional

fix(TDI-36065): make sortKey optional

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java

https://jira.talendforge.org/browse/TUP-18298

fix(TUP-18298)fileds missing when open the MapR Hadoop cluster wizard

---

main/plugins/org.talend.designer.neo4j/src/org/talend/designer/neo4j/ui/editor/MetadataTableEditorViewExt.java

https://jira.talendforge.org/browse/TUP-18325

fix(TUP-18325)Interface of Row line component display deformation

---

main/plugins/org.talend.designer.components.bigdata/components/tELTHiveMap/tELTHiveMap_java.xml

Hive jars of the emr_2.4.0 distribution are imported and leaking into the classpath of the final job.
Not importing Hive jars of the emr_2.4.0 distribution if another Hive distribution is used.

fix(TBD-5429): Unable to use multiple tELTHiveMap components

---

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml

* TBD5416 Update netty-all version to 4.0.42
* TBD5416 Revert unnecessary changes to module groups not related to Spark

TBD-5416 Update netty-all version to 4.0.42 (#424) (#434)

---

main/plugins/org.talend.designer.components.bigdata/components/tELTHiveMap/tELTHiveMap_main.javajet

https://jira.talendforge.org/browse/TDI-39029

fix(TDI-39029): fix the complier issue

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml

httpclient-4.3.3 and httpcore-4.3.3 jars are used by several module groups.
httpclient and httpcore jars are upgrated to httpclient-4.5.2 and httpcore-4.4.4.

feat(TBD-5322): Upgrade httpclient and httpcore version for cdh5.10

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_begin.javajet

Merge maintenance/6.4 into master

---

main/plugins/org.talend.designer.components.bigdata/components/tMapROjaiOutput/tMapROjaiOutput_java.xml

https://jira.talendforge.org/browse/TDI-39419

fix(TDI-39419):correct the maven path of jars.

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh550/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh570/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh580/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdp240/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdp250/plugin.xml

Jars could not be found in Nexus
Jars should be found

fix(TBD-5560/components): jar versions corrected

---

main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_main_0.10.0.x.javajet
main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.9.0.x/tKafkaInput_main_0.9.0.x.javajet

null value cause NPE
fix NPE issue

fix(TBD-5408): [tKafkaInput] NullPointerException occurs when ConsumerRecord's value is null

---

main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_main.javajet

tKafkaCommit is not working with Kafka 0.10
tKafkaCommit works with Kafka 0.10

fix(TBD-5465) : Add Kafka 0.10 support to tKafkaCommit

---

main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_main.javajet

tKafkaCommit is not working with Kafka 0.10
tKafkaCommit is working with Kafka 0.10

fix(TBD-5465) : Add Kafka 0.10 support to tKafkaCommit (#459)

---

main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_main.javajet

tKafkaCommit does not support Kafka 0.10
tKafkaCommit supports Kafka 0.10

fix(TBD-5465) : Add Kafka 0.10 support to tKafkaCommit (#459) (#460)

---

main/plugins/org.talend.designer.components.bigdata/components/tMapROjaiOutput/tMapROjaiOutput_begin.javajet

https://jira.talendforge.org/browse/TDI-39452

fix(TDI-39452):fix the keytab cannot work issue.

---

main/plugins/org.talend.designer.components.bigdata/components/tMapROjaiOutput/tMapROjaiOutput_main.javajet

https://jira.talendforge.org/browse/TDI-39444

fix(TDI-39444):Amend the reject line behavior.

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml

Issue when using spark job with tHiveOutput when we select an ORC file as Output Source.
Bug fixed.

fix(TBD-5374): orc file for spark thiveoutput issue

---

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml

fix(TBD-5535): Add commons-codec to HDP 2.6 HDFS libraries

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml

fix(TBD-5374): fix orc file for spark thiveoutput issue (#481)

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopMerge/tSqoopMerge_javaapi.javajet

DI job with tSqoopMerge does not work
https://jira.talendforge.org/browse/TBD-5801
DI job with tSqoopMerge works

fix(TBD-5801/components): fixed (DI Job with tSqoopMerge cannot run successfully)

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopMerge/tSqoopMerge_messages.properties

unknown string for tSqoopMerge
https://jira.talendforge.org/browse/TBD-5802
unknown string transformed to "common options

fix/TBD-5802: unknown string for tSqoopMerge

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopMerge/tSqoopMerge_messages.properties

unknown string for tSqoopMerge
https://jira.talendforge.org/browse/TBD-5802
unknown string transformed to "common options

fix/TBD-5802: unknown string for tSqoopMerge (#519)

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopExport/tSqoopExport_javaapi.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_javaapi.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImportAllTables/tSqoopImportAllTables_javaapi.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopMerge/tSqoopMerge_javaapi.javajet

TUJs with tSqoopxxx components are failing 
https://jira.talendforge.org/browse/TBD-5885
TUJS work correctly

fix(TBD-5885/components): Fix the Sqoop TUJs after the DRIVER_CLASSNAME parameter has been added

---

test/plugins/org.talend.hadoop.distribution.hdp250.test/src/org/talend/hadoop/distribution/hdp250/test/HDP250ClassLoaderTest.java
test/plugins/org.talend.hadoop.distribution.hdp260.test/src/org/talend/hadoop/distribution/hdp260/test/HDP260ClassLoaderTest.java

fix junit fail

---

pom.xml
test/features/org.talend.bigdata.se.test.feature/feature.xml

The test plugin was not included into its feature.xml and the aggregator pom.xml. So the CI will never execute the unit tests
https://jira.talendforge.org/browse/TBD-5921
Test plugin added to feature.xml and pom.xml

fix(TBD-5921/components): test plugin was not included into its feature.xml

---

main/plugins/org.talend.repository.hbaseprovider/src/org/talend/repository/hbaseprovider/provider/HBaseMetadataProvider.java
main/plugins/org.talend.repository.maprdbprovider/src/main/java/org/talend/repository/maprdbprovider/provider/MapRDBMetadataProvider.java

fix(TUP-18046):Cannot Retrieve Columns from Metadata MapRDB Database

---

main/plugins/org.talend.hadoop.distribution.emr550/plugin.xml

Chore(TBD-5267): Merge from 64 to 65

---

main/plugins/org.talend.designer.components.bigdata/components/tHBaseInput/tHBaseInput_messages.properties

fix(TBD-5964): Fix UI text

---

main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml

Compile error.
Add avro-mapred dependency to spark module group.

fix(TBD-5878): Add avro-mapred dependency to spark module group

---

main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml

Some dependencies for HBase group are missing.
Add missing dependencies to HBase group.

fix(TBD-5981): Add missing dependencies to HBASE group

---

main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml

Some dependencies for HBase group are missing.
Add missing dependencies to HBase group.

fix(TBD-5981): Merge maintenance/6.5 into master

---

main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml

Compile error.
Add avro-mapred dependency to spark module group.

fix(TBD-5878): Merge maintenance/6.4 to maintenance/6.5

---

main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml

fix(TBD-5985): change kafka jar version

---

main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml

fix(TBD-5985): Merge maintenance/6.5 into master

---

test/plugins/org.talend.hadoop.distribution.mapr600.test/META-INF/MANIFEST.MF

fix the junit

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/spark/SparkVersionUtil.java

No spark 2.1 available for spark custom distrib
Available for Spark Batch and Spark Streaming

fix(TBD-5954): add spark 2.1 version for custom distrib

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/spark/SparkVersionUtil.java

No spark 2.2 available for spark custom distrib
Available for Spark Batch and Spark Streaming

fix(TBD-5954): add spark 2.2 version for custom distrib

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/spark/SparkVersionUtil.java

Merge maintenance/6.5 to master

---

main/plugins/org.talend.designer.components.bigdata/components/tMapRStreamsInput/0.9.0.x/tMapRStreamsInput_main_0.9.0.x.javajet

fix(TBD-6019): fix NPE for tMapRStreamsInput

---

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jClose/tNeo4jClose_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jImportTool/tNeo4jImportTool_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml

https://jira.talendforge.org/browse/TDI-39725

fix(TDI-39725):support different return types. And fix some small bugs.

---

main/plugins/org.talend.repository.nosql/plugin.xml
main/plugins/org.talend.repository.nosql/src/messages.properties
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/mongodb/MongoDBConnectionUtil.java
test/plugins/org.talend.repository.nosql.test/src/org/talend/repository/nosql/db/util/mongodb/MongoDBConnectionUtilTest.java

- [ *] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ *] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [* ] The new code does not introduce new technical issues
do not support mongodb 3.5.x
support mongodb 3.5.x

feat(TUP-18751):Update MongoDB

---

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_main.javajet

https://jira.talendforge.org/browse/TDI-39735

fix(TDI-39735):Commit every doesn't work.

---

main/plugins/org.talend.hadoop.distribution.mapr600/plugin.xml

fix(TBD-6023): missing Gson dependency

---

main/plugins/org.talend.hadoop.distribution.mapr520/src/main/java/org/talend/hadoop/distribution/mapr520/MapR520Distribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java
test/plugins/org.talend.hadoop.distribution.mapr520.test/src/org/talend/hadoop/distribution/mapr520/test/MapR520DistributionTest.java

fix(TBD-5470): tSqlRow dependencies missing for some distribution

---

main/plugins/org.talend.rcp.branding.tos.bigdata/content/root.xhtml

feat(TUP-18946): add advertisement for Cloud product
https://jira.talendforge.org/browse/TUP-18946

feat(TUP-18946): add advertisement for Cloud product

---

main/plugins/org.talend.hadoop.distribution.mapr600/plugin.xml

fix(TBD-6035): upgrade DynamoDB and Kinesis dependencies

---

main/plugins/org.talend.hadoop.distribution.mapr600/plugin.xml

fix(TBD-5969): change wrong jar versions

---

main/plugins/org.talend.hadoop.distribution.mapr520/src/main/java/org/talend/hadoop/distribution/mapr520/MapR520Distribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java
test/plugins/org.talend.hadoop.distribution.mapr520.test/src/org/talend/hadoop/distribution/mapr520/test/MapR520DistributionTest.java

 fix(TBD-5470): tSqlRow dependencies missing for some distribution

---

main/plugins/org.talend.repository.maprdbprovider/src/main/java/org/talend/repository/maprdbprovider/provider/MapRDBMetadataProvider.java

https://jira.talendforge.org/browse/TUP-19017

fix(TUP-19017): MaprDB6 check fail on wizard

---

main/plugins/org.talend.hadoop.distribution.mapr600/src/org/talend/hadoop/distribution/mapr600/modulegroup/MapR600SparkDynamoDBNodeModuleGroup.java

fix(TBD-5470): master fix

---

main/features/org.talend.hadoop.distribution.feature/feature.xml
pom.xml
test/features/org.talend.bigdata.se.test.feature/feature.xml

- Naive attempt to fix the build

feat(TBD-6061): Remove obsolete distributions only

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_begin.javajet

This commit totally depends on https://github.com/Talend/tcommon-studio-se/pull/1303, see more details there.

feat(TBD-5414) Change the way of getting user agent

---

main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml

fix(TBD-6093): Missing dependency for HDi 3.6

---

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml

fix(TBD-6089): Missing dependency for Sqoop on HDP 2.6

---

main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml

Merge maintenance/6.5 in master

---

main/plugins/org.talend.hadoop.distribution.mapr520/plugin.xml

Unused jar "netty-3.9.0-Final.jar"
Removed.

fix(TBD-6098): remove unused jar netty

---

main/plugins/org.talend.hadoop.distribution.mapr520/plugin.xml

Merge maintenance branch 6.5 to master

---

main/features/org.talend.tos.bigdata.feature/feature.xml

Add new doc plugin for future couchbase component.
Wait to merge, component is not even integrated yet

feat(TUP-19036) Add help plugin for new couchbase component

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdh5x/cdh5xTemplate2.json

Add jodd library for MAPREDUCE_LIB_MODULE
Add 3 exclusions for Sqoop

feat(TBD-5453) Update template

---

main/plugins/org.talend.hadoop.distribution.mapr600/plugin.xml

fix(TBD-6140): Compile error when spark str job use tMaprStreamOutput with Mapr 6

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

https://jira.talendforge.org/browse/TDI-39645

Pyzhou/tdi 39645 upgrade aws java sdk.jar to version 1.11.223

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdh5x/cdh5xTemplate.json

Add IMPALA-LIB-DYNAMIC module group

Fix(TBD-6210) Fix Impala check service

---

main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/hadoop/service/check/provider/CheckedJobtrackerProvider.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/hadoop/service/check/provider/CheckedNamenodeProvider.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/hadoop/service/check/provider/CheckedResourceManagerProvider.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/manager/HadoopServerUtil.java

https://jira.talendforge.org/browse/TUP-19269
1. Set property if using KERBEROS:
hadoop.security.authentication=KERBEROS
2. Correct the error message

fix(TUP-19269): When create a CDH513 cluster by Enter Manually Hadoop services,check connection failed for HDFS

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdh5x/cdh5xTemplate.json

Add this jar graphframes-0.5.0-spark2.1-s_2.11.jar for graphframes module group

Add jar for graphframes

---

main/plugins/org.talend.hadoop.distribution.altus10/plugin.xml
main/plugins/org.talend.hadoop.distribution.altus10/src/main/java/org/talend/hadoop/distribution/altus10/modulegroup/Altus10SparkBatchModuleGroup.java
main/plugins/org.talend.hadoop.distribution.altus10/src/main/java/org/talend/hadoop/distribution/altus10/modulegroup/Altus10SparkStreamingModuleGroup.java

Missing classes/jars when running jobs on Altus/AWS
Upgraded some deps
Added missing ones

fix(TBD-6278):Missing AWS deps

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdh5x/cdh5xTemplate.json

feat(TBD-6219): Reformat cdh5xTemplate.json

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/adapter/DynamicTemplateAdapter.java

fix a templateBean cache problem which causes check service failed

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_begin.javajet

https://jira.talendforge.org/browse/TDI-39602

feat(TDI-39602):Use the new tracker implementation for AWS / google

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

https://jira.talendforge.org/browse/TDI-37863

feat(TDI-37863):Upgrade aws-java-driver to 269.

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/AbstractDynamicDistribution.java

Add property -Dtalend.studio.dynamicDistribution.template.forceRefresh=true , so that
we don't need to comment some codes to modify/test template since it is
easy to commit the commented codes.

Add property to force to refresh template cache

---

main/plugins/org.talend.hadoop.distribution.cdh540/src/main/java/org/talend/hadoop/distribution/cdh540/CDH540Distribution.java

CDH 5.4.0 is not shown anymore
CDH 5.4.0 is shown in order to allow to run the basic TUJs, waiting for a real solution. THis is a temp fix which will be reverted before the GA.

fix(TUJs): temporary fix to allow running CDH 5.4.0 TUJs again

---

test/plugins/org.talend.hadoop.distribution.mapr520.test/src/org/talend/hadoop/distribution/mapr520/test/MapR520ClassLoaderTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/HadoopDistributionsHelperTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/ImpalaDistributionsTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4AmazonEMRTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4ClouderaTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4HortonworksTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4MapRTest.java

fix(TBD-6331): Fix junit tests

---

main/plugins/org.talend.hadoop.distribution.emr400/src/main/java/org/talend/hadoop/distribution/emr400/EMR400Distribution.java
main/plugins/org.talend.hadoop.distribution.hdinsight320/src/main/java/org/talend/hadoop/distribution/hdinsight320/HDInsight32Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp230/src/main/java/org/talend/hadoop/distribution/hdp230/HDP230Distribution.java
main/plugins/org.talend.hadoop.distribution.mapr410/src/main/java/org/talend/hadoop/distribution/mapr410/MapR410Distribution.java
main/plugins/org.talend.hadoop.distribution.piv101/src/main/java/org/talend/hadoop/distribution/piv101/Pivotal101Distribution.java

deactivated: HDP 2.3, EMR 4.0.0, Mapr 4.1.0, Pivotal 1.0.1 HD Insight 3.2

---

main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraConnection/tCassandraConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutput/tCassandraOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/tCassandraOutputBulk_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraRow/tCassandraRow_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMapROjaiOutput/tMapROjaiOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakConnection/tRiakConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakKeyList/tRiakKeyList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakOutput/tRiakOutput_java.xml

Upgrade Jackson libraries for JIRA:
https://jira.talendforge.org/browse/TDI-39894
https://access.redhat.com/security/cve/cve-2017-7525
There is a security exploit that is open in the Jackson libraries used by some Talend Components. The specific issue is that a deserialization flaw was discovered in the jackson-databind which could allow an unauthenticated user to perform code execution by sending the maliciously crafted input to the readValue method of the ObjectMapper.
update jackson version to which include the fix.

 fix(TDI-39894):update jackson version

---

main/plugins/org.talend.hadoop.distribution/src/main/java/messages.properties
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/VersionNotFoundException.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/adapter/DynamicModuleAdapter.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/adapter/DynamicPluginAdapter.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/bean/ModuleBean.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/resolver/AbstractDependencyResolver.java

1. support useStudioRepository
2. don't break execution when version not found

Improve resolve dependency logic

---

main/plugins/org.talend.hadoop.distribution.emr450/plugin.xml

fix(TBD-4424):Redshift components need avro 1.7.6+ (#683)

---

main/plugins/org.talend.hadoop.distribution.emr450/plugin.xml

Merge 6.4 into 6.5

---

main/plugins/org.talend.hadoop.distribution.emr450/plugin.xml

fix(TBD-4424):Redshift components need avro 1.7.6+ (#683) (#684)

---

main/plugins/org.talend.hadoop.distribution.emr580/plugin.xml

fix(TBD-6433): Convert DynamoDB on EMR jar name to full name

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaOutput/tImpalaOutput_main.javajet

Hard coded date format
Use schema provided pattern

fix(TBD-6195): use date pattern from schema

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaOutput/tImpalaOutput_main.javajet

https://github.com/Talend/tbd-studio-se/pull/669

fix(TBD-6195): use date pattern from schema (#669)

---

main/plugins/org.talend.hadoop.distribution.emr580/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr580/src/main/java/org/talend/hadoop/distribution/emr580/EMR580Distribution.java
main/plugins/org.talend.hadoop.distribution.emr580/src/main/java/org/talend/hadoop/distribution/emr580/modulegroup/node/sparkbatch/EMR580SparkBatchAzureNodeModuleGroup.java

no Azure storage support for AMR 5.8.0
Azure Blob storage support for EMR 5.8.0

fix(TBD-6445): Azure Blob storage support for EMR 5.8.0

---

main/plugins/org.talend.hadoop.distribution.cdh5120/src/main/java/org/talend/hadoop/distribution/cdh5120/CDH5120Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh5x/CDH5xDistributionTemplate.java

Cloudera navigation version = 9 => API 1.x
Cloudera navigation version = 12 => API 2.x

fix(TBD-6500): change navigator version for dynamic distrib

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh570/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh580/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdp240/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdp250/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml

Compilation issue on tAvro components in Map Reduce jobs
Add Avro dependencies to Map Reduce dependency group.

fix(TBD-6505): avro dependencies in Map Reduce group

---

main/plugins/org.talend.hadoop.distribution.hdinsight340/src/main/java/org/talend/hadoop/distribution/hdinsight340/HDInsight34Distribution.java
main/plugins/org.talend.hadoop.distribution.hdinsight360/src/main/java/org/talend/hadoop/distribution/hdinsight360/HDInsight36Distribution.java

ADLS is disabled on HD Insight 3.4 and 3.6
ADLS is enabled

fix(TBD-6437): Enable ADLS on HDi

---

main/plugins/org.talend.hadoop.distribution.cdh5100/src/main/java/org/talend/hadoop/distribution/cdh5100/CDH5100Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh5120/src/main/java/org/talend/hadoop/distribution/cdh5120/CDH5120Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh5x/CDH5xDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution.hdp250/src/org/talend/hadoop/distribution/hdp250/HDP250Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp260/src/org/talend/hadoop/distribution/hdp260/HDP260Distribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java

Assume Role option available for all distributions
Assume Role option available for implemented distributions

fix(TBD-6211): Add Assume Role option in distribution

---

main/plugins/org.talend.designer.components.bigdata/OSGI-INF/memSQL.xml
main/plugins/org.talend.designer.components.bigdata/src/main/java/org/talend/designer/bigdata/unifiedcomponent/memSQL/MemSQLComponentsUnifier.java
main/plugins/org.talend.designer.components.bigdata/src/main/java/org/talend/designer/bigdata/unifiedcomponent/memSQL/unifier.json

MemSQl -> Apply : nothing happen

fix(TUP-19423):When using Generic DB Connector / tDBConnection / select

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMapROjaiOutput/tMapROjaiOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakConnection/tRiakConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakKeyList/tRiakKeyList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakOutput/tRiakOutput_java.xml

For JIRA: https://jira.talendforge.org/browse/TDI-39894
Upgrade jackson to 2.9.4

fix(TDI-39894):update jackson version 2.x.x to 2.9.4

---

main/plugins/org.talend.hadoop.distribution.cdh5100/src/main/java/org/talend/hadoop/distribution/cdh5100/CDH5100Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh5120/src/main/java/org/talend/hadoop/distribution/cdh5120/CDH5120Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh550/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh550/src/main/java/org/talend/hadoop/distribution/cdh550/CDH550Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh550/src/main/java/org/talend/hadoop/distribution/cdh550/CDH560Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh570/src/main/java/org/talend/hadoop/distribution/cdh570/CDH570Distribution.java
main/plugins/org.talend.hadoop.distribution.cdh580/src/main/java/org/talend/hadoop/distribution/cdh580/CDH580Distribution.java
main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml
main/plugins/org.talend.hadoop.distribution.dataproc11/src/main/java/org/talend/hadoop/distribution/dataproc11/Dataproc11Distribution.java
main/plugins/org.talend.hadoop.distribution.emr450/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr500/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr550/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr550/src/main/java/org/talend/hadoop/distribution/emr550/EMR550Distribution.java
main/plugins/org.talend.hadoop.distribution.emr580/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr580/src/main/java/org/talend/hadoop/distribution/emr580/EMR580Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp250/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdp250/src/org/talend/hadoop/distribution/hdp250/HDP250Distribution.java
main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdp260/src/org/talend/hadoop/distribution/hdp260/HDP260Distribution.java
main/plugins/org.talend.hadoop.distribution.mapr510/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr520/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr600/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr600/src/org/talend/hadoop/distribution/mapr600/MapR600Distribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/MRComponent.java

fix(TBD-6505): support avro versions by distribution

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/util/HCRepositoryUtil.java

https://jira.talendforge.org/browse/TUP-19252

fix(TUP-19252): Cann't broswer HDFS directory when main DI job use ref project HDFS

---

main/plugins/org.talend.hadoop.distribution.emr580/plugin.xml

fix(TBD-6445): typo in azure dependencies

---

main/plugins/org.talend.designer.components.bigdata/components/tPigLoad/tPigLoad_begin.javajet

An exception occured `Caused by: java.lang.IllegalArgumentException: Can not create a Path from an empty string`.
Add a filter for jars to avoid the exception.

fix(TBD-6506): Add jar filter for tPigLoad

---

test/plugins/org.talend.hadoop.distribution.cdh5120.test/src/org/talend/hadoop/distribution/cdh5120/test/modulegroup/CDH5120MapReduceModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.cdh5120.test/src/org/talend/hadoop/distribution/cdh5120/test/modulegroup/CDH5120SparkBatchModuleGroupTest.java

Review of Junits
Fix two CDH5120 failed junits.

fix(TUP-19195):fix two CDH5120 failed junits.

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml

No matches between jar versions in the studio and in the nexus
ok

fix(TBD-6579): fix nexus version cdh510 jars

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_javaapi.javajet

Java mapping is being overrided in tSqoopImport if 
https://jira.talendforge.org/browse/TBD-5491
Java mapping is preserved

TBD-5491: fix

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_javaapi.javajet

TBD-5491: fix for 6.3

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBConnection/tMongoDBConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSDelete/tMongoDBGridFSDelete_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSGet/tMongoDBGridFSGet_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSList/tMongoDBGridFSList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSProperties/tMongoDBGridFSProperties_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSPut/tMongoDBGridFSPut_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBRow/tMongoDBRow_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

https://jira.talendforge.org/browse/TBD-6109
No more issue.

fix(TBD-6109): change mongo-java jar version

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh550/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh570/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh580/plugin.xml

TBD(6474) :  Revert Jackson upgrade for CDH

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdh5x/Cloudera_CDH5_13_0_dynamic_20180226115614083_0100.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdh5x/cdh5xTemplate.json

fix: wrong dependency version

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBConnection/tMongoDBConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSDelete/tMongoDBGridFSDelete_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSGet/tMongoDBGridFSGet_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSList/tMongoDBGridFSList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSProperties/tMongoDBGridFSProperties_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSPut/tMongoDBGridFSPut_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBRow/tMongoDBRow_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

* fix(TBD-6109): change mongo-java jar version
Fix issue from 6.2 --> cherry pick

fix(TBD-6109): change mongo-java jar version (#715)

---

main/plugins/org.talend.hadoop.distribution.cdh540/src/main/java/org/talend/hadoop/distribution/cdh540/CDH540Distribution.java
main/plugins/org.talend.hadoop.distribution.piv200/src/main/java/org/talend/hadoop/distribution/piv200/Pivotal200Distribution.java

Deprecated and not functional distributions are visible
Disable the remaining deprecated distributions

fix(TBD-6548): disable CDH 5.4 and Piv 2.0

---

main/plugins/org.talend.repository.nosql/plugin.xml

Wrong version of mongo-java-driver jar on nosql wizard 
Good one.

fix(TBD-6666): change mongo-java-driver on metadata wizard

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml

fix(TBD-6692): change jar version for jaxb-impl

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml

fix(TBD-6692): change jar version for jaxb-impl (#744)

---

main/plugins/org.talend.repository.nosql/plugin.xml

fix(TBD-6666): change mongo-java-driver on metadata wizard (#740)

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/util/HCRepositoryUtil.java

https://jira.talendforge.org/browse/TUP-19781 
[SVN] Can open/run/click code my JDBC job

fix(TUP-19781):[SVN] Can't run my JDBC job.

---

main/plugins/org.talend.repository.nosql/plugin.xml

Missing jar import
Fix mvn uri for mongodb jars

fix(TBD-6705) add mvn uri definition for mongo jars

---

main/plugins/org.talend.repository.nosql/plugin.xml

fix(TBD-6705) add mvn uri definition for mongo jars 64

---

main/plugins/org.talend.repository.nosql/plugin.xml

fix(TBD-6705) add mvn uri definition for mongo jars (#754)

---

main/plugins/org.talend.repository.nosql/plugin.xml

fix(TBD-6705) add mvn uri definition for mongo jars 63

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdh5x/Cloudera_CDH5_13_0_dynamic_20180226115614083_0100.json

dynamic builtin 5.13 file name change

---

test/plugins/org.talend.hadoop.distribution.cdh580.test/src/org/talend/hadoop/distribution/cdh580/test/modulegroup/CDH580MapReduceModuleGroupTest.java

fix junit of CDH580MapReduceModuleGroupTest#testModuleGroups

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java

https://jira.talendforge.org/browse/TUP-18802

fix(TUP-18802)Cannot update hadoop version after revert context

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/dnd/HadoopClusterDragAndDropHandler.java
main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/dnd/HCatalogDragAndDropHandler.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/dnd/HDFSDragAndDropHandler.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/dnd/NoSQLDragAndDropHandler.java

https://jira.talendforge.org/browse/TUP-19974

fix(TUP-19974)Opening a job takes more than half an hour in studio

---

pom.xml

add qubole plugin

---

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml

https://jira.talendforge.org/browse/TBD-6877
The version of kite libs is updated to 1.1.0 from 1.0.0.

fix(TBD-6877): Fix kite version for hdp 2.6 with Sqoop and Parquet

---

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml

https://jira.talendforge.org/browse/TBD-6877
Update kite jars to 1.1 verion in plugin.xml

fix(TBD-6877): Fix HDP + HA with Sqoop + Parquet issue

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/mongodb/MongoDBMetadataProvider.java

https://jira.talendforge.org/browse/TUP-20142

fix(TUP-20142)Can't retrieve schema for some mongo collection

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/viewer/handler/AbstractHadoopSubnodeRepositoryContentHandler.java

https://jira.talendforge.org/browse/TUP-20124

fix(TUP-20124): NPE during changing TCOMP component repository value

---

main/features/org.talend.tos.bigdata.libraries.feature/feature.xml

https://jira.talendforge.org/browse/TUP-20173
no more warnings on feature about missing bundles.

fix(TUP-20173): fixed fragment usage in feature

---

main/plugins/org.talend.designer.components.bigdata/components/tELTHiveOutput/tELTHiveOutput_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tHiveInput/tHiveInput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tHiveLoad/tHiveLoad_main.javajet

https://jira.talendforge.org/browse/TBD-6923
Job runs successfully when Hive on TEZ is not supported by Hadoop distribution

Achursin/tbd-6923 mapr5.2 hive

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

https://jira.talendforge.org/browse/TDI-40526
Fix for tMongoDBOutput
**SHOULD BE MERGED ONLY AFTER NEXT PRs** 
https://github.com/Talend/tdi-studio-se/pull/2358
https://github.com/Talend/tcommon-studio-se/pull/1693

fix(TDI-40526): Update json-lib dependency

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/HadoopDistributionsHelperTest.java

Some unit tests are failing due to Qubole related code.
JUnit tests are fixed

fix: fix Qubole related unit tests

---

main/plugins/org.talend.designer.components.bigdata/components/tMapROjaiInput/tMapROjaiInput_begin.javajet

DI job with tMaprOjaiInput component cannot run successfully with byte data column
https://jira.talendforge.org/browse/TBD-7065
DI job with tMaprOjaiInput component run successfully with byte data column

bug/TBD-7065: fixed

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/ESparkVersion.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/spark/SparkVersionUtil.java

feat(TBD-6888) : Add Spark 2.3 to local mode

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdh5x/Cloudera_CDH5_13_0.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdh5x/cdh5xTemplate.json

https://jira.talendforge.org/browse/TBD-7190
Jar can be downloaded from repository

fix(TBD-7190): Fix missing httpcore jar for CDH 5.13

---

main/plugins/org.talend.hadoop.distribution.databricks/pom.xml

feat(TBD-6295): fix pom parent version databricks

---

main/plugins/org.talend.hadoop.distribution.databricks/META-INF/MANIFEST.MF

feat(TBD-6295): fix manifest for databricks

---

main/plugins/org.talend.hadoop.distribution.databricks/src/main/java/org/talend/hadoop/distribution/databricks/DatabricksDistribution.java

Wrong label version
Wrong spark mode
Change spark mode to standalone
Change label

feat(TBD-7191): Replace DB spark mode to standalone

---

main/plugins/org.talend.hadoop.distribution.databricks/META-INF/MANIFEST.MF
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/HadoopDistributionsHelperTest.java

feat(TBD-6295): fix junit tests

---

main/plugins/org.talend.hadoop.distribution.mapr601/plugin.xml
main/plugins/org.talend.libraries.apache.kafka/plugin.xml

fix(TBD-7221): fix jar definitions

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

https://jira.talendforge.org/browse/TDI-40679
https://jira.talendforge.org/browse/TDI-40679

fix(TDI-40679): align to httpclient-4.5.5,httpfluent-4.5.5 and httpcore-4.4.9

---

pom.xml
test/features/org.talend.bigdata.se.test.feature/feature.xml
test/plugins/org.talend.hadoop.distribution.qubole.test/.classpath
test/plugins/org.talend.hadoop.distribution.qubole.test/.project
test/plugins/org.talend.hadoop.distribution.qubole.test/META-INF/MANIFEST.MF
test/plugins/org.talend.hadoop.distribution.qubole.test/META-INF/eclipse.inf
test/plugins/org.talend.hadoop.distribution.qubole.test/build.properties
test/plugins/org.talend.hadoop.distribution.qubole.test/pom.xml
test/plugins/org.talend.hadoop.distribution.qubole.test/src/org/talend/hadoop/distribution/qubole/test/QuboleClassLoaderTest.java
test/plugins/org.talend.hadoop.distribution.qubole.test/src/org/talend/hadoop/distribution/qubole/test/QuboleDistributionTest.java
test/plugins/org.talend.hadoop.distribution.qubole.test/src/org/talend/hadoop/distribution/qubole/test/modulegroup/QuboleHiveModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.qubole.test/src/org/talend/hadoop/distribution/qubole/test/modulegroup/QubolePigModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.qubole.test/src/org/talend/hadoop/distribution/qubole/test/modulegroup/QubolePigOutputModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.qubole.test/src/org/talend/hadoop/distribution/qubole/test/modulegroup/QuboleSparkBatchModuleGroupTest.java

Add Qubole test plugin

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/repository/migration/UnifyPasswordEncryption4NoSQLConnectionMigrationTask.java

https://jira.talendforge.org/browse/TUP-20391

fix(TUP-20391): Migration tasks are re-executed and encrypting passwords

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/templates/CosmosDB/ApplicationName.javajet

feat(TDI-40559): Add partner tag to CosmosDB family

---

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml

https://jira.talendforge.org/browse/TBD-6658
Job runs succesfully

fix(TBD-6658): Fix SparkStr job with Hive orc fails on HDP26

---

main/plugins/org.talend.hadoop.distribution.mapr601/OSGI-INF/mapr601.xml
main/plugins/org.talend.hadoop.distribution.mapr601/src/org/talend/hadoop/distribution/mapr601/MapR601Distribution.java

TBD-7030: initial commit

---

main/plugins/org.talend.hadoop.distribution.custom/OSGI-INF/custom.xml
main/plugins/org.talend.hadoop.distribution.custom/src/main/java/org/talend/hadoop/distribution/custom/CustomDistribution.java

fix(TBD-7301): MapR 6.0.1 fixes

---

main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_java.xml
main/plugins/org.talend.hadoop.distribution.mapr500/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr500/src/main/java/org/talend/hadoop/distribution/mapr500/MapR500Distribution.java
main/plugins/org.talend.hadoop.distribution.mapr510/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr510/src/main/java/org/talend/hadoop/distribution/mapr510/MapR510Distribution.java
main/plugins/org.talend.hadoop.distribution.mapr520/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr520/src/main/java/org/talend/hadoop/distribution/mapr520/MapR520Distribution.java
main/plugins/org.talend.hadoop.distribution.mapr600/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr600/src/org/talend/hadoop/distribution/mapr600/MapR600Distribution.java
main/plugins/org.talend.hadoop.distribution.mapr601/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr601/src/org/talend/hadoop/distribution/mapr601/MapR601Distribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/EWinUtilsName.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/HadoopComponent.java

fix/TBD-7269: winutils problem

---

main/plugins/org.talend.hadoop.distribution.custom/OSGI-INF/custom.xml
main/plugins/org.talend.hadoop.distribution.custom/src/main/java/org/talend/hadoop/distribution/custom/CustomDistribution.java

fix(TBD-7301): MapR 6.0.1 fixes (#822)

---

main/plugins/org.talend.hadoop.distribution.mapr601/plugin.xml

TBD-7413, TBD-7414 fixed

---

main/plugins/org.talend.hadoop.distribution.mapr601/plugin.xml

fix(TBD-7384): Upgrade plugin xml

---

main/plugins/org.talend.hadoop.distribution.mapr601/plugin.xml

fix(TBD-7429): Fix Hive Maven URIs for MapR601 in plugin.xml

---

main/plugins/org.talend.hadoop.distribution.mapr601/plugin.xml

fix(TBD-7465): change maven groupId

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/hdp/IDynamicHDPDistributionPreference.java

https://jira.talendforge.org/browse/TUP-20105

feat(TUP-20105): Change hortonworks setup to set the default proxy from talend

---

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml

fix(TBD-6765): Upgrade Sqoop commons lang to 3.5

---

main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_end_0.10.0.x.javajet
main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.9.0.x/tKafkaInput_end_0.9.0.x.javajet
main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMapRStreamsInput/0.9.0.x/tMapRStreamsInput_end_0.9.0.x.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMapRStreamsOutput/tMapRStreamsOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMapRStreamsOutput/tMapRStreamsOutput_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMapRStreamsOutput/tMapRStreamsOutput_main.javajet

Adding a callback for kafka producer sending method to be able to retrieve execution exceptions.

feat(TBD-7559) Add callback for mapr stream output component

---

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml

fix(TBD-6765): Need both lang and lang3 for Sqoop

---

main/plugins/org.talend.hadoop.distribution.databricks/plugin.xml

feat(TBD-7017): Add User Agent support

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/cdh/IDynamicCDHDistributionPreference.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/hdp/IDynamicHDPDistributionPreference.java

https://jira.talendforge.org/browse/TUP-20704

item(TUP-20704): Update nexus url for dynamic distributions in studio

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdp2xx/Hortonworks_HDP_2_6_0_3_8.json

feat(TBD-7288) change distribution id

---

main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr5150/src/main/java/org/talend/hadoop/distribution/emr5150/EMR5150Distribution.java
main/plugins/org.talend.hadoop.distribution.emr5150/src/main/java/org/talend/hadoop/distribution/emr5150/modulegroup/node/sparkstreaming/EMR5150SparkStreamingKinesisNodeModuleGroup.java
main/plugins/org.talend.hadoop.distribution.emr580/src/main/java/org/talend/hadoop/distribution/emr580/EMR580Distribution.java

feat(TBD-7577): Implement Spark streaming for EMR 5.15

---

main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tHiveLoad/tHiveLoad_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tPigLoad/tPigLoad_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tPigLoad/tPigLoad_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tPigStoreResult/tPigStoreResult_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/templates/Pig/RegisterPigLatin.javajet
main/plugins/org.talend.hadoop.distribution.qubole/plugin.xml
main/plugins/org.talend.hadoop.distribution.qubole/src/main/java/org/talend/hadoop/distribution/qubole/QuboleDistribution.java

Adding more detailed information like job name, tags etc. for qubole hive job.
Components included:
- tHiveCreateTable
- tHiveLoad
- tPigLoad
- tPigStoreResult
Relates to
https://github.com/Talend/tbd-studio-ee/pull/639
https://github.com/Talend/tdi-studio-se/pull/2715

feat(TBD-7591) Add job name & tags for qubole hive/pig components

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

https://jira.talendforge.org/browse/TDI-41023

feat(TDI-41023):upgrade aws sdk

---

main/plugins/org.talend.hadoop.distribution.databricks/plugin.xml

feat(): fix bigdata launcher for databricks

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH5_13_0.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh5xTemplate.json
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/adapter/DynamicModuleAdapter.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/bean/ModuleBean.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/util/DynamicDistributionUtils.java

https://jira.talendforge.org/browse/TUP-20803

fix(TUP-20803): Bad maven reference for apache-curator

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/AbstractModuleGroup.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/dynamic/form/AbstractDynamicDistributionSetupForm.java

only print trace info in debug mode

---

main/plugins/org.talend.hadoop.distribution.custom/OSGI-INF/custom.xml
main/plugins/org.talend.hadoop.distribution.custom/src/main/java/org/talend/hadoop/distribution/custom/CustomDistribution.java

fix(TBD-7293): Add Custom distribution support to Hive on Spark

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakConnection/tRiakConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakKeyList/tRiakKeyList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakOutput/tRiakOutput_java.xml
main/plugins/org.talend.hadoop.distribution.mapr510/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr520/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr600/plugin.xml
main/plugins/org.talend.hadoop.distribution.mapr601/plugin.xml
main/plugins/org.talend.libraries.apache.kafka/plugin.xml

https://jira.talendforge.org/browse/TDI-41251
https://jira.talendforge.org/browse/TDI-41251

fix(TDI-41251): Update jackson libraries to avoid CVE-2018-15758

---

main/plugins/org.talend.repository.hbaseprovider/src/org/talend/repository/hbaseprovider/provider/HBaseMetadataProvider.java

https://jira.talendforge.org/browse/TUP-20973

fix(TUP-20973): [BUG] Failed Test Connection for HBase of dynamic CDH 6.0.0 cluster

---

main/plugins/org.talend.hadoop.distribution.qubole/plugin.xml

update bigdata launcher jar version for s3 credentials modifications.
Relates to https://github.com/Talend/tbd-studio-ee/pull/704

feat(TBD-7943) update bigdata launcher jar version

---

main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdinsight360/src/main/java/org/talend/hadoop/distribution/hdinsight360/modulegroup/HDInsight36SparkBatchModuleGroup.java

fix(TBD-7933): fix missing talend-bigdata-launcher-1.2.0-20170410.jar

---

main/plugins/org.talend.hadoop.distribution.hdinsight360/src/main/java/org/talend/hadoop/distribution/hdinsight360/HDInsight36Distribution.java

fix(TBD-7993): add support of SparkYarnClientMode in HDInsight36

---

main/features/org.talend.tos.bigdata.repository.feature/feature.xml

https://jira.talendforge.org/browse/TUP-21137

Fix : TUP-21137 Security: jtds-1.3.1-patch.jar ntlmauth loaded from a path variable

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/viewer/HadoopSubMultiRepTypeProcessor.java

fix(TUP-21145)use equals instead

---

main/plugins/org.talend.repository.hadoopcluster.configurator/src/org/apache/ambari/api/TextJacksonJsonProvider.java

HDP 3.0
https://jira.talendforge.org/browse/TUP-21087

fix(TUP-21087)[7.1.1] Retrieve from Ambari cluster config files fails in

---

main/plugins/org.talend.hadoop.distribution/src/main/java/messages.properties
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/adapter/DynamicLibraryNeededExtensionAdaper.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/adapter/DynamicModuleAdapter.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/adapter/DynamicTemplateAdapter.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/resolver/AbstractDependencyResolver.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/resolver/IDependencyResolver.java

https://jira.talendforge.org/browse/TUP-21288

item(TUP-21288): Allow to use multi-thread to collect dynamic distribution dependencies

---

main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh5x/CDH5xDistributionTemplate.java

fix(TBD-8075): Addition of slash support for AWS (#928)

---

main/plugins/org.talend.hadoop.distribution.databricks/src/main/java/org/talend/hadoop/distribution/databricks/DatabricksDistribution.java

fix(TBD-8075):Keep using old AWS api API for 7.1

---

main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml

fix(TBD-7961): Use Cloudera official jar for mllib-local on CDH 5.12 (#927)

---

main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml

fix(TBD-7988): NullPointerException in Spark Batch job with EMR 5.15

---

main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh5x/CDH5xDistributionTemplate.java

patch(TPS-2832): Addition of slash support for AWS

---

main/plugins/org.talend.hadoop.distribution.emr5150/src/main/java/org/talend/hadoop/distribution/emr5150/EMR5150Distribution.java

fix(TBD-8145): Use newer s3a key properties for EMR 5.15

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/DynamicDistributionManager.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/helper/DistributionsManager.java

https://jira.talendforge.org/browse/TUP-21176

fix(TUP-21176): Reload Dynamic Distribution jars in a right place

---

main/plugins/org.talend.hadoop.distribution.dataproc11/src/main/java/org/talend/hadoop/distribution/dataproc11/Dataproc11Distribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hive/action/CreateHiveAction.java

https://jira.talendforge.org/browse/TUP-20519
hide GoogleDataproc for hive on wizard.

fix(TUP-20519):hide GoogleDataproc for hive on wizard.

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/resolver/cdh/ClouderaDependencyResolver.java

https://jira.talendforge.org/browse/TUP-20987

fix(TUP-20987):Could not initialize class error when check hive for dynamic CDH513.

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hive/action/CreateHiveAction.java

fix(TUP-20519):Not supported yet on studio,so all the test / retrieve must be disabled on this distribution.

---

main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml

fix(TBD-8181): update jackson dependencies for EMR 5.15

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/QuboleInfoForm.java

https://jira.talendforge.org/browse/TUP-21551

Fix:TUP-21551 Qubole:Cluster label don't show context value after you convert it

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

* upgrade commons-collections from 3.2.1 to 3.2.2
for https://jira.talendforge.org/browse/TDI-41506

fix(TDI-41506):High CVE Vulnerability found in Talend Components

---

main/plugins/org.talend.hadoop.distribution.databricks/src/main/java/org/talend/hadoop/distribution/databricks/DatabricksDistribution.java

fix(TBD-8107): support S3a in Databricks

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_begin.javajet

https://jira.talendforge.org/browse/TDI-41634

fix(TDI-41634):AWS role is not working for Dynamodb

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/cdh/AbstractDynamicCDHDistributionTemplate.java

https://jira.talendforge.org/browse/TUP-21710
https://jira.talendforge.org/browse/TUP-21710

fix(TUP-21710):tImpalaConnection component not able to build libraries in 7.1.1

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/AbstractDynamicDistributionPreference.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/neo4j/Neo4jMetadataProvider.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/mongodb/MongoDBConnectionUtil.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/neo4j/Neo4jConnectionUtil.java

tcommon-studio-ee
https://jira.talendforge.org/browse/TUP-21205

bugfix(TUP-21205):Remove CryptoHelper from tcommon-studio-se +

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/AbstractDynamicDistributionPreference.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/neo4j/Neo4jMetadataProvider.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/mongodb/MongoDBConnectionUtil.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/neo4j/Neo4jConnectionUtil.java

Reverts Talend/tbd-studio-se#971

Revert "bugfix(TUP-21205):Remove CryptoHelper from tcommon-studio-se +"

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/DynamicDistributionManager.java

fix:remove unwanted override annotation

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_main_below_3_5.javajet

Compile error
No compile error 

fix(TDI-41553): Fix compile error when old mongo version used

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBConnection/tMongoDBConnection_begin.javajet

After final check for https://jira.talendforge.org/browse/TDI-41396
CURSOR_FINALIZER_ENABLED parameter not appears in generated code
Typo in javajet file was corrected.

feat(TDI-41396): correct parameter cursorFinalizerEnabled

---

main/plugins/org.talend.repository.hadoopcluster.configurator/src/org/talend/repository/hadoopcluster/configurator/RetrieveConfigurationProcess.java

https://jira.talendforge.org/browse/TUP-21777
https://jira.talendforge.org/browse/TUP-21777

fix(TUP-21777):[7.0.1] Metadata Wizard with SSL cannot retrieve cluster settings

---

main/plugins/org.talend.oozie.scheduler/plugin.xml
main/plugins/org.talend.oozie.scheduler/src/messages.properties
main/plugins/org.talend.oozie.scheduler/src/org/talend/oozie/scheduler/views/TOozieView.java
main/plugins/org.talend.repository.oozie/plugin.properties
main/plugins/org.talend.repository.oozie/plugin.xml
main/plugins/org.talend.repository.oozie/src/messages.properties
main/plugins/org.talend.repository.oozie/src/org/talend/repository/oozie/ui/OozieWizard.java

https://jira.talendforge.org/browse/TUP-21337

feat(TUP-21337):Deprecate oozie (view/preferences)

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/QuboleInfoForm.java

run->spark configuration view
https://jira.talendforge.org/browse/TUP-21662

bugfix(TUP-21662):API endpoint &region are shown as context value on

---

main/plugins/org.talend.oozie.scheduler/src/messages.properties
main/plugins/org.talend.oozie.scheduler/src/org/talend/oozie/scheduler/ui/OozieMonitoringComposite.java

fix(TUP-22145)Error pops up after clicked accept license when

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdp2xx/Hortonworks_HDP_2_6_0_3_8.json

https://jira.talendforge.org/browse/TUP-22281

TUP-22281 Missing jar in lib folder for Job Server

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdp2xx/Hortonworks_HDP_2_6_0_3_8.json

https://jira.talendforge.org/browse/TUP-22281 revert to last commit

TUP-22281 Missing jar in lib folder for Job Server(Reverted)

---

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_begin.javajet

https://jira.talendforge.org/browse/TDI-41944
https://jira.talendforge.org/browse/TDI-41944

fix(TDI-41944): [Java 11] Replace usage of sun.misc.Base64 to java.util.Base64

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/ESparkVersion.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/spark/SparkVersionUtil.java

Add Spark version 2.4 in utility classes

feat(TBD-8385): Support Spark 2.4 local mode

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4MapRTest.java

https://jira.talendforge.org/browse/TBD-8620
Fixed

TBD-8620: fixed

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

fix(TBD-8589):ClassNotFoundException if di job use tSqoopExport,Import,Merge,AllTables

---

main/plugins/org.talend.hadoop.distribution.mapr610/plugin.xml

https://jira.talendforge.org/browse/TUP-23016

fix(TUP-23016):Jar download issue for azure-storage.

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json
main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh6x/CDH6xDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/DynamicSparkBatchModuleGroup.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/DynamicSparkStreamingModuleGroup.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/cdh/DynamicCDHSparkBatchModuleGroup.java

Cdh611 spark batch

---

main/plugins/org.talend.designer.components.bigdata/components/tCouchDBClose/tCouchDBClose_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBConnection/tCouchDBConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBInput/tCouchDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBOutput/tCouchDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBReadConf/tCouchDBReadConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBWriteConf/tCouchDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMemSQLClose/tMemSQLClose_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMemSQLConnection/tMemSQLConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMemSQLInput/tMemSQLInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMemSQLOutput/tMemSQLOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMemSQLRow/tMemSQLRow_java.xml

https://jira.talendforge.org/browse/TDI-42316

Fix(TDI-42316):Deprecation.

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/adapter/DynamicPluginAdapter.java

https://jira.talendforge.org/browse/TUP-23036

fix(TUP-23036): Can't run spark job when I select CDH513ker as distribution

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakConnection/tRiakConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakKeyList/tRiakKeyList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakOutput/tRiakOutput_java.xml

fix(TDI-42396): Upgrade jackson to 2.9.9

---

main/plugins/org.talend.hadoop.distribution.emr450/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr500/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr550/plugin.xml

https://jira.talendforge.org/browse/TUP-23168

fix(TUP-23168)Install external library issues

---

main/plugins/org.talend.designer.components.bigdata/components/tHiveInput/tHiveInput_begin.javajet

feat(TBD-8684): add SSL support to Impala components (update from @carlos review)

---

main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml

fix(TDI-42396): Fix wrong module name for tRiakBucketList

---

main/plugins/org.talend.hadoop.distribution.databricks/plugin.xml

feat(TBD-8604):Update Big Data Launcher to 1.3.2

---

main/plugins/org.talend.hadoop.distribution.mapr610/plugin.xml

old jackson libs with cve
fresh libs without cve

Jackson cve fix

---

main/plugins/org.talend.hadoop.distribution.mapr610/plugin.xml

Jackson libs added

---

main/plugins/org.talend.hadoop.distribution.mapr610/plugin.xml

fix(): json maven uri

---

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml
main/plugins/org.talend.repository.nosql/plugin.xml

https://jira.talendforge.org/browse/TDI-42503
https://jira.talendforge.org/browse/TDI-42503

fix(TDI-42503): fix the neo4j tuj failed which is caused by we add logback jar always for TIS

---

main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh6x/CDH6xDistributionTemplate.java

fix(TBD-8427/TBD-8770):Enable s3a for CDH 6

---

main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh6x/CDH6xDistributionTemplate.java

fix(TBD-8427/TBD-8770):Enable s3a for CDH 6 (#1043)

---

main/plugins/org.talend.hadoop.distribution.mapr610/plugin.xml

https://jira.talendforge.org/browse/TBD-8804
Fixed

TBD-8804: fixed

---

main/plugins/org.talend.hadoop.distribution.mapr610/plugin.xml

* TBD-8804: fixed
* All occurences of org.talend.libraries corrected

fix(TBD-8804): 

---

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml
main/plugins/org.talend.repository.nosql/plugin.xml

This reverts commit 5ed94ec08f6883e946aadc31bbea8d6e12f707a5.
https://jira.talendforge.org/browse/TDI-42503
https://jira.talendforge.org/browse/TDI-42503

Revert "fix(TDI-42503): fix the neo4j tuj failed which is caused by we add (#1039)"

---

main/plugins/org.talend.hadoop.distribution.mapr610/plugin.xml

fix(TBD-8804): Update plugin.xml (conflicting uris with components team)

---

main/plugins/org.talend.hadoop.distribution.mapr610/plugin.xml

https://jira.talendforge.org/browse/TBD-8851
Fixed

TBD-8851: fixed

---

main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/creator/HCatalogConnectionCreator.java

https://jira.talendforge.org/browse/TUP-23225

TUP-23225 Hiveserver2 host is not correctly discovered in the studio

---

main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_main.javajet

update tKafkaInput component TBD-8800

---

main/plugins/org.talend.hadoop.distribution.mapr610/plugin.xml

https://jira.talendforge.org/browse/TBD-8889
Fixed

fix(TBD-8889): [MapR 6.1] Incompatible Jackson version: 2.9.9 on batch and streaming jobs

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/AbstractDynamicDistributionPreference.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/resolver/AbstractDependencyResolver.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/resolver/cdh/ClouderaDependencyResolver.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/resolver/hdp/HortonworksDependencyResolver.java

https://jira.talendforge.org/browse/TUP-21435

fix(TUP-21435):Dynamic distributions of CDH can get different kinds of errors.

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

…veContext without HiveComponents to cdh611 built-in distribution

fix(TBD-7708): Unable to instantiate SparkSession on tSqlRowComponent

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaClose/tImpalaClose_main.javajet

couldn't get information since node name is tImpalaConnection instead of
tHiveConnection.

fix(TBD-8989): code looks for tImpalaConnection to close it.

---

main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaConnection/tSAPHanaConnection_begin.javajet

https://jira.talendforge.org/browse/TDI-42670
https://jira.talendforge.org/browse/TDI-42670

fix(TDI-42670): tSAPHanaoutput uses the globalMap.get("username_tDBConnection_1")) which isn't defined by tSAPHanaConnection

---

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh580spark2/plugin.xml

fix(TBD-7446):Sync with TDQ about overlapping dependencies in components

---

main/plugins/org.talend.hadoop.distribution.dbr540/plugin.xml

fix a path for a dependency in plugin.xml for databricks 5.4

fix(TBD-7858): support transient cluster mode for databricks

---

main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml

fix(TBD-8932): fix compile error for HDInsight

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaClose/tImpalaClose_main.javajet

couldn't get information since node name is tImpalaConnection instead of
tHiveConnection.

fix(TBD-8989): tImpala calls the good code instead of trying to use Hive code, it

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaClose/tImpalaClose_main.javajet

fix(TBD-8989): refacto of tImpalaClose to match with last PR

---

main/plugins/org.talend.designer.components.bigdata/components/tKafkaConnection/tKafkaConnection_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_messages.properties

fix(TBD-9093): fix incorrect field name for Kafka components in di

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaClose/tImpalaClose_main.javajet

patch(TPS-3274): tImpalaClose component not closing the connection

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/HadoopComponent.java

fix(TBD-9148) : ADLS Gen2 not available for CDH > 6.1

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

https://jira.talendforge.org/browse/TDI-42689

fix(TDI-42689) : Uprade js-lib to 2.4.2-talend

---

main/plugins/org.talend.repository.hadoopcluster.configurator/src/org/talend/repository/hadoopcluster/configurator/cloudera/HadoopCMConfigurator.java
test/plugins/org.talend.repository.hadoopcluster.configurator.test/src/main/test/org/talend/repository/hadoopcluster/configurator/cloudera/test/ClouderaHadoopConfig512Test.java

https://jira.talendforge.org/browse/TUP-24330
No behavior changes

fix(TUP-24330) Cannot retrieve conf from cdh512

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

* Update json-lib version in components

fix(TDI-37801): tWriteJSONField null values

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_begin.javajet

https://jira.talendforge.org/browse/TDI-42659

fix(TDI-42659):reduce log level to trace tCosmosDB.

---

main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/controllers/AbstractHDFSBrowseController.java

fix(TUP-23077)left border of text of component tFileCopy does not show

---

main/plugins/org.talend.repository.hadoopcluster.configurator/src/org/talend/repository/hadoopcluster/configurator/cloudera/HadoopCMConfigurator.java

https://jira.talendforge.org/browse/TUP-24385
No behavior changes

fix(TUP-24385) Can not connect hadoop cluster

---

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_finally.javajet

https://jira.talendforge.org/browse/TDI-42748

fix(TDI-42748):tNeo4JRow compile error

---

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_finally.javajet

* fix(TDI-42748):tNeo4JRow compile error
* fix(TDI-42748):tNeo4JRow compile error
https://jira.talendforge.org/browse/TDI-42748

fix(TDI-42748):tNeo4JRow compile error (#1093)

---

main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml

fix(TBD-8932): fix compile error for HDInsight (#1081)

---

tools/list-distributions-ids.py

We do not any tools to list the distributions ids.
add a script to list them. 
this is related to https://jira.talendforge.org/browse/TBD-8812 (first step)

TBD-8812: add script to list all distributions ids

---

main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml

fix(TBD-9192): added missing jar for EMR Kinesis

---

main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml

fix(TBD-9202) : Update Big Data launcher lib to 1.3.4 for Dataproc 1.1

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/HadoopDistributionsHelperTest.java
test/plugins/org.talend.repository.hadoopcluster.test/src/main/java/org/talend/repository/hadoopcluster/conf/RetrieveLocalConfsServiceTest.java

fix(TBD-7936): fix unit tests for hdp 2.4

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdp2xx/Hortonworks_HDP_2_6_0_3_8.json
main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdp2xx/hdp2xxTemplate.json

fix(TBD-9204): Missing Jar jettison-1.3.4.jar when using Hive through Dynamic distro HDP 2.6.3-128-2

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaConnection/tImpalaConnection_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tImpalaInput/tImpalaInput_begin.javajet

TBD-9268: Impala Job not working in 7.2.1

---

main/plugins/org.talend.hadoop.distribution.mapr610/src/org/talend/hadoop/distribution/mapr610/MapR610Distribution.java

TBD-9230 and TBD-9229: switching mapr to use new s3 AWS API instead of old one

---

main/plugins/org.talend.hadoop.distribution.dataproc14/.project
main/plugins/org.talend.hadoop.distribution.dbr540/plugin.xml

set the new talend-bigdata-launcher-platform as dependency of Databricks 5.4 distribution

fix(TBD-9316): Set the new version of talend-bigdata-launcher-platform for Databricks

---

main/plugins/org.talend.rcp.branding.tos.bigdata/resources/NOTICE.txt

Wrong license in NOTICE.txt
Correct Apache license in NOTICE.txt

chore(DEVOPS-7875): Fix NOTICE license type

---

pom.xml

remove some non used part of the pom.

clean non used part of pom

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/AbstractDynamicDistributionPreference.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/cdh/AbstractDynamicCDHDistributionPreference.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/cdh/IDynamicCDHDistributionPreference.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/hdp/AbstractDynamicHDPDistributionPreference.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/hdp/IDynamicHDPDistributionPreference.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/repository/migration/UnifyPasswordEncryption4NoSQLConnectionMigrationTask.java

https://jira.talendforge.org/browse/TUP-21518
No behavior changes
No behavior changes

feat(TUP-21518) Remove CryptoHelper

---

main/plugins/org.talend.repository.pigudf/build.properties

https://jira.talendforge.org/browse/TUP-24863
Fix wrong project settings

fix (TUP-24863) set back build.properties to normal

---

main/plugins/org.talend.repository.hadoopcluster.configurator/.classpath
main/plugins/org.talend.repository.hadoopcluster.configurator/META-INF/MANIFEST.MF

TBD-9421: add missing okkio dependency in Manifest

---

test/plugins/org.talend.hadoop.distribution.dataproc14.test/src/org/talend/hadoop/distribution/dataproc14/test/Dataproc14DistributionTest.java

Current tests is asserting the distribution support Kerberos. This is not the case
Fix the test

fix(TBD-9516) : fix google dataproc 1.4 test plugin

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaClose/tImpalaClose_main.javajet

fix(TBD-9491): tImpalaClose component seems not to closing connection in subjobs

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_begin.javajet

https://jira.talendforge.org/browse/TDI-43198
https://jira.talendforge.org/browse/TDI-43198

fix(TDI-43198): tdynamoDBInput ignores the column names containing '-'

---

main/plugins/org.talend.designer.components.bigdata/components/tMemSQLConnection/tMemSQLConnection_java.xml

fix(TDI-43211): SharedDBConnectionLog4j use log4j1 api, should use slf4j

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp3xxTemplate.json

fix(TBD-9654): [HDP3.1] add missing mvnUri in distribution template

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH5_13_0.json

fix(TBD-9362): re-generating cdh513 dependencies

---

main/plugins/org.talend.hadoop.distribution.hdpx/src/org/talend/hadoop/distribution/hdpx/HDP3xxDistributionTemplate.java

Override the method to activate ADLS Gen2 on HDP 3.1

feat(TBD-8983): Support ADLS Gen2 on HDP 3.1

---

main/plugins/org.talend.repository.hbaseprovider/src/org/talend/repository/hbaseprovider/provider/HBaseMetadataProvider.java

fix(TBD-9612): fix HBaseMetadataProvider for schema editor & test connection

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/node/sparkstreaming/hdp/DynamicHDPSparkStreamingKinesisNodeModuleGroup.java

add spark 2.2, 2.3, 2.4 for dynamic HDP so the classes are loaded

fix(TBD-9687): Compile error on tKinesisInput / tKinesisInputAvro

---

main/plugins/org.talend.hadoop.distribution.dbr350/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml

fix(TBD-9712): update dependencies on launcher

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_begin.javajet

https://jira.talendforge.org/browse/TDI-42659
https://jira.talendforge.org/browse/TDI-42659

fix(TDI-42659):reduce log level to trace tCosmosDB. (#1099)

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaClose/tImpalaClose_main.javajet

… in subjobs (#1162)
* fix(TBD-9491): tImpalaClose component seems not to closing connection in subjobs

patch(TPS-3608): tImpalaClose component seems not to closing connection in subjobs

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_begin.javajet

https://jira.talendforge.org/browse/TDI-41634

fix(TDI-41634):AWS role is not working for Dynamodb (#972)

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_begin.javajet

Dchmyga/tdi 43418 backport to 7.2

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_begin.javajet

* Process List instead of BasicDBList

fix(TDI-43418): MongoDB Date objects in array (#1198)

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

…n: com.amazonaws.auth.AWSCredentials

fix(TBD-9455): tDynamoDbInput, tDynamoDbOutput: ClassNotFoundException: com.amazonaws.auth.AWSCredentials

---

main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr350/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml

Fix the maven URI for talend-bigdata-launcher

fix(TBD-9807): Missing jar

---

main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml

fix(TBD-9807): fix jar's name

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

Reverts Talend/tbd-studio-se#1210

Revert "fix(TBD-9455): tDynamoDbInput, tDynamoDbOutput: ClassNotFoundException: com.amazonaws.auth.AWSCredentials"

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

fix(TDI-40449): upgrade dynamoDB dependency

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdh5x/Cloudera_CDH5_13_0.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdh5x/cdh5xTemplate.json

fix(TBD-9582): backport to 7.0: library version issue with CDH 5.13

---

main/components_lib/talend-lineage-api/pom.xml
main/components_lib/talend-lineage-api/src/test/java/org/talend/lineage/atlas/AtlasLineageCreatorIT.java
main/components_lib/talend-lineage-api/src/test/java/org/talend/lineage/cloudera/DriverITCDH513Test.java
main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdh5x/Cloudera_CDH5_13_0.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdh5x/cdh5xTemplate.json

fix(TBD-9362): backport to 70: re-building lineage jar and updating version of this jar for cdh5.12 and cdh5.13 dynamic distributions

---

main/components_lib/talend-lineage-api/pom.xml
main/components_lib/talend-lineage-api/src/test/java/org/talend/lineage/atlas/AtlasLineageCreatorIT.java
main/components_lib/talend-lineage-api/src/test/java/org/talend/lineage/cloudera/DriverITCDH513Test.java
main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdh5x/Cloudera_CDH5_13_0.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdh5x/cdh5xTemplate.json

Contains changes from: 
https://github.com/Talend/tbd-studio-se/pull/1222
https://github.com/Talend/tbd-studio-se/pull/1223

patch(TPS-3571): Big Data Batch Spark job Cloudera Navigator lineage failing(TBD-9362, TBD-9789, TBD-9582)

---

main/plugins/org.talend.hadoop.distribution.cdh5120/src/main/java/org/talend/hadoop/distribution/cdh5120/modulegroup/CDH5120MapReduceModuleGroup.java
main/plugins/org.talend.hadoop.distribution.cdh5120/src/main/java/org/talend/hadoop/distribution/cdh5120/modulegroup/CDH5120SparkBatchModuleGroup.java

fix(TBD-9769): adding Lineage dependencies to Yarn Cluster submission mode

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH5_13_0.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh5xTemplate.json

fix(TBD-9582): backport to 7.2: library version issue with CDH 5.13

---

main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/hadoop/service/check/provider/CheckedNamenodeProvider.java
main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/manager/HadoopServerUtil.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/service/HadoopClusterService.java

https://jira.talendforge.org/browse/TUP-25727

fix(TUP-25727):Dataviewer for hdfs schema failed if it's checked webHDFS encryption

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH5_13_0.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh5xTemplate.json

fix(TBD-9582): backport to 7.1: library version issue with CDH 5.13

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaOutput/tImpalaOutput_java.xml

fix(TBD-9862): tImpalaOutput is unavailable

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBConnection/tMongoDBConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSDelete/tMongoDBGridFSDelete_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSGet/tMongoDBGridFSGet_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSList/tMongoDBGridFSList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSProperties/tMongoDBGridFSProperties_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSPut/tMongoDBGridFSPut_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBRow/tMongoDBRow_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

https://jira.talendforge.org/browse/TDI-43511

feat(TDI-43511):Upgrade mongoDB driver

---

main/features/org.talend.tos.bigdata.feature/feature.xml

https://jira.talendforge.org/browse/TUP-25786

feat(TUP-25786): Enable online help

---

main/components_lib/talend-lineage-api/pom.xml
main/components_lib/talend-lineage-api/src/test/java/org/talend/lineage/atlas/AtlasLineageCreatorIT.java
main/components_lib/talend-lineage-api/src/test/java/org/talend/lineage/cloudera/DriverITCDH513Test.java
main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH5_13_0.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh5xTemplate.json

fix(TBD-9362): backport to 71: re-building lineage jar and updating version of this jar for cdh5.12 and cdh5.13 dynamic distributions

---

main/components_lib/talend-lineage-api/pom.xml
main/components_lib/talend-lineage-api/src/test/java/org/talend/lineage/atlas/AtlasLineageCreatorIT.java
main/components_lib/talend-lineage-api/src/test/java/org/talend/lineage/cloudera/DriverITCDH513Test.java
main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH5_13_0.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh5xTemplate.json

fix(TBD-9362): backport for 7.2: re-building lineage jar and updating version of this jar for cdh5.12 and cdh5.13 distributions

---

main/plugins/org.talend.designer.components.bigdata/components/tPigLoad/tPigLoad_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tPigStoreResult/tPigStoreResult_java.xml

fix(TBD-9791): correct  maven url for jaxen lib

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_3_1_4_12_1.json

fix(TBD-9820):Jars conflict issue using Kinesis input/output components

---

main/plugins/org.talend.designer.components.bigdata/components/tHCatalogInput/tHCatalogInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHCatalogLoad/tHCatalogLoad_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHCatalogOperation/tHCatalogOperation_java.xml

fix(TBD-9948): Compile error for tHCatalog components

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java

https://jira.talendforge.org/browse/TUP-25976

fix(TUP-25976):Authentication field is move below.

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

Reverts Talend/tbd-studio-se#1248

Revert "fix(TDI-43610): jsonutil bump version to 2.4.5-talend"

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

https://jira.talendforge.org/browse/TDI-43610

fix(TDI-43610): jsonutil bump version to 2.4.5-talend

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/service/NOSQLService.java

bugfix(TUP-26031):Cannot connect successfully for mongDB

---

main/plugins/org.talend.hadoop.distribution.emr550/plugin.xml

fix(TBD-9886): update httpcore and httpclient lib

---

main/plugins/org.talend.rcp.branding.tos.bigdata/plugin.properties
main/plugins/org.talend.rcp.branding.tos.bigdata/resources/license.txt

https://jira.talendforge.org/browse/TUP-26123
Update copyright date to 2020

fix(TUP-26123): Update copyright date

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_begin.javajet

* Process List instead of BasicDBList

fix(TDI-43418): MongoDB Date objects in array (#1198) (#1201)

---

main/plugins/org.talend.hadoop.distribution.hdinsight340/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml

Update bigdata-launcher-version in HDInsight distributions to use the one that fix the TBD-10041.

fix(TBD-10041): return code issue on job creation

---

test/plugins/org.talend.hadoop.distribution.hdinsight360.test/src/org/talend/hadoop/distribution/hdinsight360/test/HDInsight36ClassLoaderTest.java

fix(TBD-10052): ignore some JUNIT classloader test

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

https://jira.talendforge.org/browse/TDI-43610

fix(TDI-43610): jsonutil bump v2.4.5-talend

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

* fix(TDI-43631): Update json-lib dependency
* fix(TDI-43631): Bump json-lib-talend version

fix(TDI-43772): Add all TPS in bigdata plugin to branch patch/7.1.1

---

main/plugins/org.talend.hadoop.distribution.dbr350/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml

fix(TBD-9986): removed Authorization token from logs

---

main/plugins/org.talend.designer.components.bigdata/components/templates/HDFS/GetFileSystem.javajet

fix(TBD-10157): advanced options need to be applied 

---

main/plugins/org.talend.repository.nosql/src/messages.properties
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/common/mongodb/IMongoDBAttributes.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/mongodb/MongoDBDNDProvider.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/mongodb/MongoDBConnForm.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/mongodb/MongoDBConnectionUtil.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/service/NOSQLService.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/common/AbstractNoSQLConnForm.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/context/handler/NoSQLRepositoryContextHandler.java

fix(TUP-26155):Talend to MongoDB with SSL Connection

---

main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml

fix(TBD-10212): added dependencies for avro

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_2_6_0_3_8.json

fix(TBD-9956): update hdpx 'build-in'

---

main/plugins/org.talend.repository.nosql/src/messages.properties
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/common/mongodb/IMongoDBAttributes.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/mongodb/MongoDBDNDProvider.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/mongodb/MongoDBConnForm.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/mongodb/MongoDBConnectionUtil.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/service/NOSQLService.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/common/AbstractNoSQLConnForm.java

fix(TUP-26155):Talend to MongoDB with SSL Connection (#1291)

---

main/plugins/org.talend.repository.nosql/src/messages.properties
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/common/mongodb/IMongoDBAttributes.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/mongodb/MongoDBDNDProvider.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/mongodb/MongoDBConnForm.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/mongodb/MongoDBConnectionUtil.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/service/NOSQLService.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/common/AbstractNoSQLConnForm.java

fix(TUP-26155):Talend to MongoDB with SSL Connection.

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_javaapi.javajet
main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml

https://jira.talendforge.org/browse/TBD-10095
Fixed for javaapi+avro

fix(TBD-10095): Sqoop issue with parquet/avro format with EMR 5.15(2.8.3)

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/mongodb/MongoDBConnectionUtil.java

fix(TUP-26155):fix compilation error

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

fix(TBD-10213): fix java.lang.NoClassDefFoundError for cdh 6.1

---

main/plugins/org.talend.repository.nosql/src/messages.properties
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/common/mongodb/IMongoDBAttributes.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/mongodb/MongoDBDNDProvider.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/mongodb/MongoDBConnForm.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/mongodb/MongoDBConnectionUtil.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/service/NOSQLService.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/common/AbstractNoSQLConnForm.java

TPS-3909:[7.3.1] DI job with Big Data components fail when using the custom hadoop conf file location feature(TUP-26580)

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_commandline.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_java.xml
main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml

fix(TBD-10095): patch for 7.1.1

---

main/plugins/org.talend.repository.nosql/src/messages.properties
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/factory/NoSQLRepositoryTranslator.java

fix(TUP-25739): the label in metadata is not match the one in mongodb

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_commandline.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_javaapi.javajet
main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdp2xx/Hortonworks_HDP_2_6_0_3_8.json
main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdp2xx/hdp2xxTemplate.json
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/hdp/DynamicHDPSparkBatchModuleGroup.java

fix(TBD-9956): fix Sqoop issue for hdp 2.x

---

tools/commit-check.py

chore(TBD-10338): Allow TPS in commit-check.py

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_begin.javajet

https://jira.talendforge.org/browse/TDI-44034

fix(TDI-44034):remove useless coma.

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

add a comma to CDH 6x template

fix(TBD-10443):CDH 6.X not available in the wizard

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

fix(TBD-10340): [Spark Streaming, CDH 6.1] NoClassDefFoundError on tH…-R2020-05_TBD

---

main/plugins/org.talend.hadoop.distribution.altus10/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json
main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr350/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdinsight340/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml
main/plugins/org.talend.hadoop.distribution.qubole/plugin.xml

fix(TBD-10436): Hive component fails with java.lang.NoClassDefFoundError_R2020-05_TBD

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBBulkLoad/tMongoDBBulkLoad_main.javajet

fix(TDI-44221): Updated output message parsing template due to driver update.

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_2_6_0_3_8.json
main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp2xxTemplate.json

fix(TBD-10412): fix broken wizard for hdp2x

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

patch(TBD-10606): remove hive-exec-1.2.1 dependency for cdh6.1 disto

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_3_5_X.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_below_3_5.javajet

https://jira.talendforge.org/browse/TDI-44253
Remove duplicate column from ROOT and LOOP tables

fix(TDI-44253): tMongoDBOutput dates processing

---

main/plugins/org.talend.hadoop.distribution.mapr601/plugin.xml

fix(TBD-10541): Upgrade jackson dependencies to 2.9.10 for MapR 6.0.1

---

main/plugins/org.talend.hadoop.distribution.mapr601/plugin.xml

fix(TBD-10541): Upgrade jackson dependencies to 2.9.10 for MapR 6.0.1_patch 7.1.1

---

main/plugins/org.talend.designer.components.bigdata/components/tMemSQLOutput/tMemSQLOutput_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet

(cherry picked from commit 9bff97ae56b0e37aa7a40b6a00d11ba927670ca2)
Backport of https://github.com/Talend/tbd-studio-se/pull/1374 into "maintenance/7.3" branch.

fix(TDI-30505): Backport from "master" to "maintenance/7.3" branch

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

fix(TBD-10506): InvalidClassException when I run a spark job with file components with CDH 611 ker

---

main/plugins/org.talend.designer.components.bigdata/components/tDBFSConnection/tDBFSConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSGet/tDBFSGet_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSPut/tDBFSPut_java.xml

fix(TBD-10585): adding missing commons-logging dependency

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/constants/cdh/altus/IClouderaAltusDistribution.java

fix(TBD-10695): Deprecate Altus

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/cdp/IDynamicCDPDistributionPreference.java

fix(TBD-10798): R2020.6 : Wrong repository url / password with proxy on dynamic distribution

---

test/plugins/org.talend.hadoop.distribution.hdinsight360.test/src/org/talend/hadoop/distribution/hdinsight360/test/HDInsight36ClassLoaderTest.java
test/plugins/org.talend.hadoop.distribution.hdinsight360.test/src/org/talend/hadoop/distribution/hdinsight360/test/HDInsight36DefaultConfigurationTest.java
test/plugins/org.talend.hadoop.distribution.hdinsight360.test/src/org/talend/hadoop/distribution/hdinsight360/test/HDInsight36DistributionTest.java
test/plugins/org.talend.hadoop.distribution.hdinsight400.test/src/org/talend/hadoop/distribution/hdinsight400/test/HDInsight40ClassLoaderTest.java
test/plugins/org.talend.hadoop.distribution.hdinsight400.test/src/org/talend/hadoop/distribution/hdinsight400/test/HDInsight40DefaultConfigurationTest.java
test/plugins/org.talend.hadoop.distribution.hdinsight400.test/src/org/talend/hadoop/distribution/hdinsight400/test/HDInsight40DistributionTest.java

fix unit test relative to PR #1454 https://github.com/Talend/tbd-studio-se/pull/1454/files#diff-83e43d86c5fd59208046f5687c3a38cbL259-L271

fix(TBD-10748): fix unit tests

---

Jenkinsfile

chore(TBD-10823): remove non working build

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_3_5_X.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_below_3_5.javajet

fix(TDI-44253): tMongoDBOutput dates processing (#1419)

---

main/plugins/org.talend.designer.components.bigdata/components/tELTHiveOutput/tELTHiveOutput_main.javajet

fix(TBD-10740):R2020-07: fixed compile error

---

main/plugins/org.talend.designer.components.bigdata/components/tELTHiveOutput/tELTHiveOutput_main.javajet

fix(TBD-10740): master: fixed compile error

---

main/plugins/org.talend.designer.components.bigdata/components/tHBaseConnection/tHBaseConnection_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tHDFSConnection/tHDFSConnection_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tImpalaConnection/tImpalaConnection_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tImpalaInput/tImpalaInput_begin.javajet

…SConnection after Studio patch:
revert tHDFSConnection, tHBaseConection, tImpalaConnection, tImpalaInput changes from TBD-10152

fix(TBD-10838): 'URLClassLoader cannot be resolved to a type' in tHDFSConnection after Studio patch

---

main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml

Backport of #1467 to master.
Fix in master.

feat(TDI-44039): update version of dataproc (#1467)

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBBulkLoad/tMongoDBBulkLoad_main.javajet

fix(TDI-44234): Ensure parallel threads terminates before Main thread stops.

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp2xxTemplate.json

fix(TBD-10863): HDP 2.x cannot be found in dynamic distributions list

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp2xxTemplate.json

fix(TBD-10863): hdp 2.x is not available: extra comma in template

---

Jenkinsfile

chore(TBD-10889): remove completely maven build

---

main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml

fix(TBD-10845): NoClassDefFoundError: org/apache/xbean/asm6/ClassVisitor

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_2_6_0_3_8.json

fix(TBD-10886): missing dependency

---

main/plugins/org.talend.repository.hbaseprovider/src/org/talend/repository/hbaseprovider/provider/HBaseMetadataProvider.java

https://jira.talendforge.org/browse/TUP-19797

fix(TUP-19797):Retrieve hbase schema can get duplicated columns

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/adapter/DynamicLibraryNeededExtensionAdaper.java

https://jira.talendforge.org/browse/TUP-26981

fix(TUP-26981):Dynamic Distribution subtasks not completing at one go.

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_begin.javajet

https://jira.talendforge.org/browse/TDI-44494

fix(TDI-44494):duplicated name in tmongodbinput m73

---

main/plugins/org.talend.designer.components.bigdata/components/tCassandraInput/tCassandraInput_datastax_begin.javajet

https://jira.talendforge.org/browse/TDI-44324
https://jira.talendforge.org/browse/TDI-44324

fix(TDI-44324): tCassandraInput doesn't have generation code when column is char type

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_begin.javajet

back port changes to master
https://jira.talendforge.org/browse/TDI-44494

fix(TDI-44494):duplicated variable name in tMongoDBInput

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaConnection/tImpalaConnectionUtilImpalaDriver.javajet

fix(TBD-10952): R2020.7: Cherry pick failed to connect impala with SSL and kerberos enabled  

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

https://jira.talendforge.org/browse/TDI-44481
https://jira.talendforge.org/browse/TDI-44481

fix(TDI-44481): CVE: commons-beanutils:commons-beanutils:1.9.3

---

main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_main.javajet

Backport of https://github.com/Talend/tbd-studio-se/pull/1375 into "maintenance/7.3" branch

Fix of useless commit for tSAPHanaOutput component.

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_3_5_X.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_below_3_5.javajet

https://jira.talendforge.org/browse/TDI-44614
Data of date type with same JSON path will process only once.
If dates with same JSON path have same pattern exception will be thrown.
This fix was tested directly with customer.

fix(TDI-44614): tMongoDBOutput dates cast problem

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp2xxTemplate.json

* fix(TBD-10900): InvalidClassException: org.apache.avro.specific.SpecificRecordBase; local class incompatible:' after applying TPS-4149

fix(TBD-10900): InvalidClassException: org.apache.avro.specific.SpecificRecordBase

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

fix(TBD-10914): fixing hive-exec, adding missing libraries

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml

https://jira.talendforge.org/browse/TDI-44481
https://jira.talendforge.org/browse/TDI-44481

fix(TDI-44481): upgrade commons-beanutils to 1.9.4

---

main/plugins/org.talend.hadoop.distribution.mapr601/src/org/talend/hadoop/distribution/mapr601/MapR601Distribution.java

fix(TBD-11040): fix tMapRDBLookupInput

---

main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_main.javajet

Reverts Talend/tbd-studio-se#1375

Revert "fix(TDI-30522): Fix of useless commit for tSAPHanaOutput component."

---

main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_main.javajet

Reverts Talend/tbd-studio-se#1495

Revert "Fix of useless commit for tSAPHanaOutput component."

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json
main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh6x/CDH6xDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/AbstractDynamicDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/DynamicModuleGroupConstant.java

feat(TBD-11007): LightWeight dependencies

---

main/plugins/org.talend.designer.components.bigdata/components/tCouchDBConnection/tCouchDBConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBInput/tCouchDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBOutput/tCouchDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBReadConf/tCouchDBReadConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBWriteConf/tCouchDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakConnection/tRiakConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakKeyList/tRiakKeyList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakOutput/tRiakOutput_java.xml

- [X ] The new code does not introduce new technical issues

fix(TDI-44486): backport to master branch.

---

main/plugins/org.talend.hadoop.distribution.mapr610/plugin.xml

fix(TBD-11077): add avro-1.8.1.jar to MapR610

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

fix(TBD-10878): Spark UI interface problem

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

fix (TBD-10878): Spark UI interface problem (org.glassfish.jersey.servlet.ServletContainer.service)

---

main/plugins/org.talend.hadoop.distribution.dbr350/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml

feat(TBD-10362): Add pool ID to databricks (#1436)

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/pref/cdp/IDynamicCDPDistributionPreference.java

fix(TBD-10798): R2020.6 : Wrong repository url / password with proxy on dynamic distribution (#1457)

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

fix(TBD-10878): Spark UI interface problem (#1557)

---

main/plugins/org.talend.hadoop.distribution.cdp/pom.xml

fix(TBD-11123): update version in pom.xml of cdp plugin

---

main/plugins/org.talend.hadoop.distribution.cdp/META-INF/MANIFEST.MF

fix(TBD-11125): update MANIFEST.MF cdp version

---

Jenkinsfile
tools/version-check.py

chore(TBD-11126): add step to check for version consistency of pom and manifest

---

Jenkinsfile
tools/version-check.py

(cherry picked from commit 16acc96481507299dc29b75d048545d583185180)

chore(TBD-11126): maintenance/7.3: add step to check for version consistency of pom and manifest

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopExport/tSqoopExport_commandline.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_commandline.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImportAllTables/tSqoopImportAllTables_commandline.javajet

fix(TBD-11081): fixed parameters concatenantion

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_2_6_0_3_8.json
main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp2xxTemplate.json

…sing dependencies in hdp 2.x)

fix(TBD-11046): Kafka spark big data streaming doesn't work well (missing dependencies)

---

main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_main.javajet

Backport of https://github.com/Talend/tbd-studio-se/pull/1571 into "master" branch

fix(TDI-30522): backport to "master"

---

main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_main.javajet

fix(TDI-30522): reworked fix.

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_2_6_0_3_8.json

hotfix incorrect json

---

main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_main.javajet

This reverts commit 38ac05420e327e2c7a0d7326730bc53f53ad1b1a.
for jira: https://jira.talendforge.org/browse/TDI-30522
Revert all fixes.

fix(TDI-30522): revert all fixes

---

tools/version-check.py

test plugins are not check against version of the branch. this make job failed after the whole project has been build. we should check this before any build (fail fast)
The script is checking also test plugins versions.

fix(TBD-11185): version_check: ensure test plugins are also tested

---

tools/version-check.py

fix(TBD-11185): maintenance/7.3: version_check: ensure test plugins are also tested

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

https://jira.talendforge.org/browse/TDI-44755

feat(TDI-44755):upgrade aws version.

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

https://jira.talendforge.org/browse/TDI-44755

feat(TDI-44755):upgrade aws version. (#1579)

---

main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_main.javajet
main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh6x/CDH6xDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution.cdp/src/main/java/org/talend/hadoop/distribution/cdp/CDP7xDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution.hdpx/src/org/talend/hadoop/distribution/hdpx/HDP3xxDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/EParquetPackagePrefix.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/MRComponent.java

TBD-10291
linked to PR https://github.com/Talend/tbd-studio-ee/pull/1756
backport of https://github.com/Talend/tbd-studio-se/pull/1332

fix(TBD-10291): R2020.9:  fix parquet prefix package for HDP3 and CDH6 

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4AmazonEMRTest.java

fix(TBD-11257): fix unit tests

---

main/plugins/org.talend.hadoop.distribution.dbr640/plugin.xml

fix(TBD-11260): R2020.09 : databricks 6.4.0 : add guava for tTopBy Component

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdp2xx/Hortonworks_HDP_2_6_0_3_8.json
main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdp2xx/hdp2xxTemplate.json

…sing dependencies in hdp 2.x) (#1564)

fix(TBD-11046): Kafka spark big data streaming doesn't work well(missing dependencies)

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4HortonworksTest.java

fix(TBD-11332): fix Junit Tests

---

main/plugins/org.talend.hadoop.distribution.mapr610/src/org/talend/hadoop/distribution/mapr610/MapR610Distribution.java

fix(TBD-11316): fix MapR610 to use hbase 2x

---

continuous-integration/Jenkinsfile

feat(TBD-11186): maintenance 7.3: add patch build on PR for maintenance branches

---

continuous-integration/Jenkinsfile

feat(TBD-11186): add patch build on PR for maintenance branches

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_begin.javajet

https://jira.talendforge.org/browse/TDI-44934

fix(TDI-44934):Regex compile error tCosmosInput

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

fix(TBD-11313): shade commons-lang3 from hive-exec

---

main/plugins/org.talend.designer.components.bigdata/components/tHCatalogInput/tHCatalogInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHCatalogLoad/tHCatalogLoad_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHCatalogOperation/tHCatalogOperation_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHCatalogOutput/tHCatalogOutput_java.xml

fix(TBD-11146): Update CXF to 3.3.6 due to CVE-2020-1954

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBConnection/tMongoDBConnection_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSDelete/tMongoDBGridFSDelete_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSGet/tMongoDBGridFSGet_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSList/tMongoDBGridFSList_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSProperties/tMongoDBGridFSProperties_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSPut/tMongoDBGridFSPut_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBRow/tMongoDBRow_messages.properties

fix(TDI-44321): Fix ssl label mongo connection

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBConnection/tMongoDBConnection_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSDelete/tMongoDBGridFSDelete_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSGet/tMongoDBGridFSGet_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSList/tMongoDBGridFSList_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSProperties/tMongoDBGridFSProperties_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSPut/tMongoDBGridFSPut_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBRow/tMongoDBRow_messages.properties

fix(TDI-44321): Capitalize studio word

---

main/plugins/org.talend.hadoop.distribution.mapr601/src/org/talend/hadoop/distribution/mapr601/MapR601Distribution.java
main/plugins/org.talend.hadoop.distribution.mapr610/src/org/talend/hadoop/distribution/mapr610/MapR610Distribution.java

fix(TBD-11388): Compilation error with MapRDBOutput component

---

main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml

fix(TBD-11309): fix bigdata launcher issue for hdi 3.6

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/AbstractDynamicDistributionTemplate.java

fix(TBD-11355): custom class path is used in lightweightmode

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/AbstractDynamicDistributionTemplate.java

fix(TBD-11355): custom class path is used in lightweightmode (#1636)

---

main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml

fix(TBD-11399): ClassNotFound fixed

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

fix(TBD-11491): missing dependency for kinesis streaming

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json

fix(TBD-11491): missing dependency for kinesis streaming (#1688)

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_3_5_X.javajet

https://jira.talendforge.org/browse/TDI-44985
ObjectId on source are transform to String on target.
When precise "__DOLLARS__oid on target data, it transform to ObjectId

fix(TDI-44985): treat __DOLLARS__

---

test/plugins/org.talend.oozie.scheduler.test/src/messages_fragment.properties

feat(TUP-28793)remove message properties

---

main/plugins/org.talend.designer.components.bigdata/components/tHDFSCopy/tHDFSCopy_java.xml

fix(TBD-11521): add mapred lib to tHDFSCopy

---

main/plugins/org.talend.designer.components.bigdata/components/tHDFSCopy/tHDFSCopy_java.xml

fix(TBD-11521): add mapred lib to tHDFSCopy (#1695)

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_3_5_X.javajet

https://jira.talendforge.org/browse/TDI-44985

fix(TDI-44985): mongo objectid

---

main/plugins/org.talend.hadoop.distribution.emr550/plugin.xml

fix(TBD-11325): lib update to fix runtime exception

---

main/plugins/org.talend.hadoop.distribution.emr550/plugin.xml

fix(TBD-11325): lib update to fix runtime exception (#1638)

---

main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh6x/CDH6xDistributionTemplate.java

fix(TBD-11369):  java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream

---

main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh6x/CDH6xDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution.cdp/src/main/java/org/talend/hadoop/distribution/cdp/CDP7xDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java

fix(TBD-11560): fix for lightweight classpath

---

main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh6x/CDH6xDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution.cdp/src/main/java/org/talend/hadoop/distribution/cdp/CDP7xDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java

fix(TBD-11560): fix for lightweight classpath (#1719)

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java

fix(TBD-11560): missing change for lightweight classpath

---

main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java

fix(TBD-11561): Patch emr529 cp 11463 11561 11543 11382 (#1716)

---

main/plugins/org.talend.hadoop.distribution.dataproc14/src/main/java/org/talend/hadoop/distribution/dataproc14/Dataproc14Distribution.java

fix(TBD-11599): Remove default setup to maven for spark.sql.hive.metastore.jars prop

---

main/plugins/org.talend.designer.components.bigdata/components/tDBFSGet/tDBFSGet_main.javajet

fix(TBD-11454): tDBFSGet:Can't get file from dbfs to local directory

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java

fix(TBD-11560): missing change (#1723)

---

main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml

fix(TBD-11663): Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Level

---

main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml

…efFoundError: org/apache/log4j/Level

fix(TBD-11763): log4j issue

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/DynamicHBaseModuleGroup.java

fix(TBD-11656): set HBsae module groups as MR_REQUIRED

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/DynamicHBaseModuleGroup.java

fix(TBD-11656): set HBase module groups as MR_REQUIRED (#1745)

---

main/plugins/org.talend.hadoop.distribution.mapr611/META-INF/MANIFEST.MF
main/plugins/org.talend.hadoop.distribution.mapr611/pom.xml

feat(TBD-11035): Support MapR 6.1 with MEP 6.1.1 - master build fix

---

main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_main.javajet

fix(TBD-11732): fix condition on set application name

---

main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_main.javajet

* fix(TBD-11732): fix condition on set application name
* fix

fix(TBD-11732): fix condition on set application name (#1764)

---

main/plugins/org.talend.repository.hadoopcluster.configurator/pom.xml

chore(TUP-29397): try add exclude transitive

---

main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_main.javajet

https://jira.talendforge.org/browse/TDI-30522

fix(TDI-30522):Address Useless commit log issue

---

main/plugins/org.talend.libraries.hadoop/META-INF/MANIFEST.MF

https://jira.talendforge.org/browse/TUP-21116
Fix test case compilation error because of Access restriction: The type 'ToolRunner' is not API

chore(TUP-21116): fix compilation error

---

main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraConnection/tCassandraConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraInput/tCassandraInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutput/tCassandraOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/tCassandraOutputBulk_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraRow/tCassandraRow_java.xml

https://jira.talendforge.org/browse/TDI-45311

fix(TDI-45311):upgrade guava version.

---

continuous-integration/Jenkinsfile

fix(TBD-11856): deactivate quick-build

---

main/plugins/org.talend.designer.components.bigdata/components/tHDFSGet/tHDFSGet_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHDFSInput/tHDFSInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHDFSList/tHDFSList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHDFSOutput/tHDFSOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHDFSOutputRaw/tHDFSOutputRaw_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHDFSProperties/tHDFSProperties_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHDFSPut/tHDFSPut_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHDFSRename/tHDFSRename_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHDFSRowCount/tHDFSRowCount_java.xml

chore(TUP-29386): remove org.talend.libraries.jetty urlpath

---

main/plugins/org.talend.repository.hadoopcluster.configurator/pom.xml

chore(TUP-29394): CVE on guava related jars

---

main/plugins/org.talend.designer.components.bigdata/components/tHCatalogInput/tHCatalogInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHDFSInput/tHDFSInput_java.xml

https://jira.talendforge.org/browse/TDI-45260
Aligning Talend file enhanced library version with TDI vesion.

fix(TDI-45260): update talend file enhanced library

---

main/plugins/org.talend.hadoop.distribution.cdp/resources/builtin/cdp/Cloudera_CDP_7_1_1.json
main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json
main/plugins/org.talend.hadoop.distribution.cdp/src/main/java/org/talend/hadoop/distribution/cdp/CDP7xDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/cdp/DynamicCDPSparkBatchModuleGroup.java

fix(TBD-11772):S3 component doesn't work on CDP 7.1.1

---

main/plugins/org.talend.hadoop.distribution.cdp/resources/builtin/cdp/Cloudera_CDP_7_1_1.json
main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json
main/plugins/org.talend.hadoop.distribution.cdp/src/main/java/org/talend/hadoop/distribution/cdp/CDP7xDistributionTemplate.java

* fix(TBD-11772): fixed missing module group for s3
* fix(TBD-11772): missing dependencies

fix(TBD-11772):S3 component doesn't work on CDP 7.1.1 (#1774)

---

main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml

fix(TBD-11817):wrong maven URI for jsch-0.1.55.jar

---

main/plugins/org.talend.hadoop.distribution.cdp/resources/builtin/cdp/Cloudera_CDP_7_1_1.json
main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json
main/plugins/org.talend.hadoop.distribution.cdp/src/main/java/org/talend/hadoop/distribution/cdp/CDP7xDistributionTemplate.java

feat(TBD-11264): support Assume role on CDP 7.1.1 (#1803)

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/manual/cdhx/Cloudera_CDH6_3_2_dynamic_20201201110315335_0100.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/manual/cdhx/Cloudera_CDH6_3_3_dynamic_20210105112305128_0100.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/manual/cdhx/README.md

fix(TBD-11701): adding cdh632 and cdh633 generated dynamic distributions to git

---

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/manual/cdhx/Cloudera_CDH6_3_2_dynamic_20201201110315335_0100.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/manual/cdhx/Cloudera_CDH6_3_3_dynamic_20210105112305128_0100.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/manual/cdhx/README.md

fix(TBD-11701): adding cdh632 and cdh633 generated dynamic distributions

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_2_6_0_3_8.json
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/AbstractDynamicDistributionTemplate.java

fix(TBD-10691): deprecate hdp2x

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_2_6_0_3_8.json
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/AbstractDynamicDistributionTemplate.java

fix(TBD-10691): deprecate hdp2x (#1808)

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakConnection/tRiakConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakKeyList/tRiakKeyList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakOutput/tRiakOutput_java.xml

https://jira.talendforge.org/browse/TDI-45418

fix(TDI-45418):Upgrade Jackson libraries

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopExport/tSqoopExport_commandline.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_commandline.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImportAllTables/tSqoopImportAllTables_commandline.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopMerge/tSqoopMerge_commandline.javajet

fix(TBD-11936): tsqoop component printing password in log

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakConnection/tRiakConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakKeyList/tRiakKeyList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakOutput/tRiakOutput_java.xml

Reverts Talend/tbd-studio-se#1797

Revert "fix(TDI-45418):Upgrade Jackson libraries"

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopExport/tSqoopExport_commandline.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_commandline.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopImportAllTables/tSqoopImportAllTables_commandline.javajet
main/plugins/org.talend.designer.components.bigdata/components/tSqoopMerge/tSqoopMerge_commandline.javajet

* TBD-11936: fixed
* tSqoopMerge fix

fix(TBD-11936): tsqoop component printing password in log (#1819)

---

main/plugins/org.talend.hadoop.distribution.spl30x/src/main/java/org/talend/hadoop/distribution/spl30x/SPL30xDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/constants/SparkBatchConstant.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/constants/SparkStreamingConstant.java

Zshen/chor/tdq 18966 support spark3 for tAlsModel and tRecommend

---

test/plugins/org.talend.hadoop.distribution.hdp260.test/src/org/talend/hadoop/distribution/hdp260/test/modulegroup/node/sparkstreaming/HDP260SparkStreamingKafkaAssemblyModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.hdp260.test/src/org/talend/hadoop/distribution/hdp260/test/modulegroup/node/sparkstreaming/HDP260SparkStreamingKinesisNodeModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.mapr500.test/src/org/talend/hadoop/distribution/mapr500/test/modulegroup/MapR500MRS3NodeModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.mapr500.test/src/org/talend/hadoop/distribution/mapr500/test/modulegroup/MapR500SparkBatchS3NodeModuleGroupTest.java

fix(TBD-12049):Fix unit tests

---

test/plugins/org.talend.hadoop.distribution.hdp260.test/src/org/talend/hadoop/distribution/hdp260/test/modulegroup/node/sparkstreaming/HDP260SparkStreamingKafkaAssemblyModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.hdp260.test/src/org/talend/hadoop/distribution/hdp260/test/modulegroup/node/sparkstreaming/HDP260SparkStreamingKinesisNodeModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.mapr500.test/src/org/talend/hadoop/distribution/mapr500/test/modulegroup/MapR500MRS3NodeModuleGroupTest.java
test/plugins/org.talend.hadoop.distribution.mapr500.test/src/org/talend/hadoop/distribution/mapr500/test/modulegroup/MapR500SparkBatchS3NodeModuleGroupTest.java

fix(TBD-12049):Fix unit tests (#1860)

---

main/plugins/org.talend.designer.components.bigdata/components/tDBFSConnection/tDBFSConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSGet/tDBFSGet_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSPut/tDBFSPut_java.xml
main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr640/plugin.xml

fix(TBD-11684): activate all transient options for databricks (#1832)

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/HadoopDistributionsHelperTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4ClouderaTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4HortonworksTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4MapRTest.java

fix(TBD-11955): fix distribution versions in unit tests for HDP, CDH, MapR

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/HadoopDistributionsHelperTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4ClouderaTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4HortonworksTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4MapRTest.java

fix(TBD-11955): fix distribution versions in unit tests for HDP, CDH, and MapR (#1866)

---

main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml

feat(TBD-11080): upgrade emr* and aws-java-sdk* libraries

---

main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml
main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml

feat(TBD-11080): upgrade emr* and aws-java-sdk* libraries (#1864)

---

main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml

fix(TBD-11569): Update google jars version (#1839)

---

main/plugins/org.talend.designer.components.bigdata/components/tHBaseConnection/tHBaseConnection_java.xml

fix(TBD-11987): thbaseconnection configured with mapr 5.0 fails to compile with 731 R2020-12 patch

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4ClouderaTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4HortonworksTest.java

fix unit tests

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4ClouderaTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4HortonworksTest.java

fix unit tests (#1873)

---

main/components_lib/talend-lineage-api/pom.xml

chore(deps-dev): bump junit in /main/components_lib/talend-lineage-api

---

main/components_lib/talend-lineage-api/pom.xml

chore(deps-dev): bump junit in /main/components_lib/talend-lineage-api (#1878)

---

continuous-integration/commit-check.py

fix(TBD-12189): add TDQ tickets in check-commit 

---

continuous-integration/commit-check.py

fix(TBD-12189): add TDQ tickets (#1890)

---

main/plugins/org.talend.repository.hadoopcluster.configurator/pom.xml

chore(TUP-29397): CVE on jackson-core-2.4.6.jar

---

main/plugins/org.talend.designer.components.bigdata/components/tDBFSConnection/tDBFSConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSGet/tDBFSGet_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSPut/tDBFSPut_java.xml
main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr640/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr73x/plugin.xml

fix(TBD-12169):Spark Jobs failing on databricks after recently adding a new property modification_time (#1896)

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBBulkLoad/tCosmosDBBulkLoad_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBBulkLoad/tMongoDBBulkLoad_main.javajet

https://jira.talendforge.org/browse/TDI-45725
Backport of https://github.com/Talend/tbd-studio-se/pull/1414 fix for tMongoDBBulkLoad into tCosmosDBBulkLoad component.

fix(TDI-45725): avoid IndexOutOfBoundsException for tCosmosDBBulkLoad component.

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBBulkLoad/tCosmosDBBulkLoad_main.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBBulkLoad/tMongoDBBulkLoad_main.javajet

fix(TDI-45725): avoid IndexOutOfBoundsException for tCosmosDBBulkLoad component. (#1895)

---

main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml

feat(TBD-11944): upgrage bigdata-launcher for Dataproc (#1888)

---

test/plugins/org.talend.hadoop.distribution.dbr73x.test/src/main/java/org/talend/hadoop/distribution/dbr73x/test/modulegroup/DBR73xSparkBatchModuleGroupTest.java

fix JUnit test in dbr73

---

test/plugins/org.talend.hadoop.distribution.dbr73x.test/src/main/java/org/talend/hadoop/distribution/dbr73x/test/modulegroup/DBR73xSparkBatchModuleGroupTest.java

fix JUnit test in dbr73 (#1915)

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4ClouderaTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4HortonworksTest.java

fix(TBD-12274): fix unit tests on master

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaConnection/tImpalaConnectionUtil.javajet

fix(TBD-12196):Impalarow not working as expected

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaConnection/tImpalaConnectionUtil.javajet

fix(TBD-12196):Impalarow not working as expected (#1920)

---

main/plugins/org.talend.designer.components.bigdata/components/tDBFSConnection/tDBFSConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSGet/tDBFSGet_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSPut/tDBFSPut_java.xml
main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr640/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr73x/plugin.xml

fix(TBD-12203): allow API retry on error 429

---

main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraConnection/tCassandraConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutput/tCassandraOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/tCassandraOutputBulk_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraRow/tCassandraRow_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml

https://jira.talendforge.org/browse/TDI-45655

fix(TDI-45727):CVE jackson-mapper-asl

---

main/plugins/org.talend.designer.components.bigdata/components/tDBFSConnection/tDBFSConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSGet/tDBFSGet_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSPut/tDBFSPut_java.xml
main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr640/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr73x/plugin.xml

fix(TBD-12203): allow API retry on error 429 (#1928)

---

main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraConnection/tCassandraConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutput/tCassandraOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/tCassandraOutputBulk_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraRow/tCassandraRow_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml

fix(TDI-45727): CVE jackson-maooer (#1903)

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp3xxTemplate.json

chore(TBD-12304):CVE on httpclient-4.5.6.jar (#1936)

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaClose/tImpalaClose_main.javajet

refacto of tImpalaClose to match with last PR

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_messages.properties

https://jira.talendforge.org/browse/TDI-45787

fix(TDI-45787): fix incorrect wording.

---

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_messages.properties
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_messages.properties

fix(TDI-45787): fix incorrect wording. (#1924)

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_commandline.javajet

fix(TBD-11722): fixed sqoop logging

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_commandline.javajet

fix(TBD-11722): fixed sqoop logging (#1937)

---

main/plugins/org.talend.hadoop.distribution.spl30x/plugin.xml

fix(TBD-12154): SPL30x : classNotFound with multiline option in tFileInputDelimited (#1942)

---

main/plugins/org.talend.hadoop.distribution/META-INF/MANIFEST.MF
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/bean/ModuleBean.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/resolver/AbstractDependencyResolver.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/resolver/hdp/HortonworksDependencyResolver.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/dynamic/adapter/DynamicModuleAdapterTest.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/dynamic/resolver/AbstractDependencyResolverTest.java

fix(TBD-12253):HDP 2.6.5 - Generated json is incomplete (#1910)

---

main/plugins/org.talend.designer.components.bigdata/components/tDBFSConnection/tDBFSConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSGet/tDBFSGet_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDBFSPut/tDBFSPut_java.xml
main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr640/plugin.xml
main/plugins/org.talend.hadoop.distribution.dbr73x/plugin.xml

fix(TBD-12079):Support Cluster Policy for Databricks transient clusters (#1930)

---

main/plugins/org.talend.designer.components.bigdata/plugin.xml

- [x ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [x ] The new code does not introduce new technical issues
https://jira.talendforge.org/browse/TDI-45753
https://jira.talendforge.org/browse/TDI-45753

fix(TDI-45753): tKafkaInput plugin.xml fix LZ4

---

main/plugins/org.talend.designer.components.bigdata/plugin.xml

fix(TDI-45753): tKafkaInput plugin.xml fix LZ4 (#1967)

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

fix(TBD-12305): CVE json-smart-2.2.1.jar

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

fix(TBD-12305): CVE json-smart-2.2.1.jar (#1974)

---

main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/HCatalogSchemaForm.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSSchemaForm.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/common/AbstractNoSQLSchemaForm.java

https://jira.talendforge.org/browse/TUP-30377

fix(TUP-30377):TUP-30377 Move the "Allow specific characters (UTF8,...)" preference setting to project setting.

---

main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/HCatalogSchemaForm.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSSchemaForm.java
main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/common/AbstractNoSQLSchemaForm.java

Feat TUP-30377 Move the utf8 (#1980)

---

main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/HCatalogSchemaForm.java

Feat TUP-30377 Move the utf8 (Improve the code) (#1982)

---

main/plugins/org.talend.designer.components.bigdata/components/tHDFSOutput/tHDFSOutput_java.xml

fix(TBD-12142): CVE: jersey-core-1.4 and jersey-1.9 (#1976)

---

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml

https://jira.talendforge.org/browse/TDI-45824
For Neo4J components : jersey version >= 2.2 : upgrade to 1.19. Older versions won't be fixed

fix(TDI-45824): Update jersey for Neo4j

---

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml

fix(TDI-45824): Update for neo4j 2.1 also

---

main/plugins/org.talend.designer.components.bigdata/components/tCouchDBConnection/tCouchDBConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBInput/tCouchDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBOutput/tCouchDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBReadConf/tCouchDBReadConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCouchDBWriteConf/tCouchDBWriteConf_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakConnection/tRiakConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakKeyList/tRiakKeyList_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tRiakOutput/tRiakOutput_java.xml

https://jira.talendforge.org/browse/TDI-46005

chore(TDI-46005): cve bump httpclient

---

main/plugins/org.talend.designer.components.bigdata/components/tHCatalogInput/tHCatalogInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHCatalogLoad/tHCatalogLoad_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHCatalogOperation/tHCatalogOperation_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tHCatalogOutput/tHCatalogOutput_java.xml

fix(TBD-12358): CVE: Update CXF to 3.3.10

---

pom.xml

https://jira.talendforge.org/browse/TBD-12133
Add new module

fix(TBD-12133): add new module

---

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml

Dsylaiev/tdi 46060 revert for neo4j 21x and 1xx (#1998)

---

test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/hive/HiveMetadataHelper4AmazonEMRTest.java

add EMR 6.2 version to unit test (#2006)

---

main/plugins/org.talend.designer.components.bigdata/components/tHCatalogInput/tHCatalogInput_java.xml

fix(TBD-12358): fix tHCatalogInput

---

main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.9.0.x/tKafkaInput_end_0.9.0.x.javajet

https://jira.talendforge.org/browse/TDI-45986

fix(TDI-45986): remove handling of unsupported exceptions.

---

main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.9.0.x/tKafkaInput_end_0.9.0.x.javajet

fix(TDI-45986): remove handling of unsupported exceptions. (#1985)

---

main/plugins/org.talend.hadoop.distribution.emr62x/plugin.xml

fix(TBD-12528):[BUG] Spark Streaming: Runtime exception on job with tRedshiftOutput component on EMR 6.2 cluster (#2021)

---

main/plugins/org.talend.designer.components.bigdata/plugin.xml

https://jira.talendforge.org/browse/TDI-46115

fix(TDI-46115): update "snappy-java" GAV coordinates.

---

main/plugins/org.talend.designer.components.bigdata/plugin.xml

fix(TDI-46115): update "snappy-java" GAV coordinates. (#2024)

---

main/plugins/org.talend.hadoop.distribution.emr62x/plugin.xml

fix(TBD-12614):[BUG] Runtime exception on Spark Batch job with Hive components, using 'orc' table format (#2030)

---

main/plugins/org.talend.hadoop.distribution.cdp/resources/builtin/cdp/Cloudera_CDP_7_1_1.json
main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json
main/plugins/org.talend.hadoop.distribution.cdp/src/main/java/org/talend/hadoop/distribution/cdp/CDP7xDistributionTemplate.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java

fix(TBD-12339):Support of Knox for CDP Data Hub Clusters AWS Public Cloud TECH PREVIEW (#1986)

---

main/plugins/org.talend.hadoop.distribution.cdp/resources/builtin/cdp/Cloudera_CDP_7_1_1.json
main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json

fix(TBD-12339):Upgrade bigdata-launcher-core-2.1.2.jar

---

main/plugins/org.talend.hadoop.distribution.cdp/resources/builtin/cdp/Cloudera_CDP_7_1_1.json
main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json

fix(TBD-12339):Upgrade bigdata-launcher-core-2.1.2.jar (#2039)

---

main/plugins/org.talend.hadoop.distribution.cdp/resources/builtin/cdp/Cloudera_CDP_7_1_1.json
main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json

fix(TBD-12671): [BUG] "java.lang.NoSuchMethodError: org.talend.bigdata.launcher.utils.Utils.removeLastSlash" is reported when using knox (#2044)

---

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/resolver/cdp/CDPDependencyResolver.java
test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/dynamic/resolver/AbstractDependencyResolverTest.java

fix(TBD-12718):CDP - incomplete generated json (#2053)

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaInput/tImpalaInput_begin.javajet

fix(TBD-12283): fixed compile error

---

main/plugins/org.talend.designer.components.bigdata/components/tImpalaInput/tImpalaInput_begin.javajet

fix(TBD-12283): fixed compile error (#2051)

---

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_begin.javajet
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_messages.properties

https://jira.talendforge.org/browse/TDI-46340

fix(TDI-46340): tMongoDB convert Bson to Json.

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_3_1_4_12_1.json

fix(TBD-12577) - deprecated HDP 3 in builtin

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_3_1_4_12_1.json

fix(TBD-12577) - deprecated HDP 3 in builtin (#2047)

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/mongodb/MongoDBMetadataProvider.java

https://jira.talendforge.org/browse/TUP-32015

Fix:TUP-32015 Guess schema datatype mapping issue in mongoDb metadata

---

main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/mongodb/MongoDBMetadataProvider.java

Fix:TUP-32015 Guess schema datatype mapping issue in mongoDb metadata (#2059)

---

main/plugins/org.talend.repository.hbaseprovider/plugin.xml
main/plugins/org.talend.repository.maprdbprovider/plugin.xml

fix(TBd-12218): upgrade zookeeper

---

main/plugins/org.talend.repository.hbaseprovider/plugin.xml
main/plugins/org.talend.repository.maprdbprovider/plugin.xml

fix(TBd-12218): upgrade zookeeper (#2067)

---

main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/sqoop-avro-dependency.javajet
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH5_13_0.json

fix(TBD-12713):tSqoopImport sometimes encountering error when exporting to AVRO file (#2065)

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

https://jira.talendforge.org/browse/TDI-46427
https://jira.talendforge.org/browse/TDI-46427

fix(TDI-46427): upgrade json-smart for tdynamicdb in bd plugins as TBD-12738 will be done in Aug

---

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml

fix(TDI-46427): upgrade json-smart for tdynamicdb in bd plugins as TBD-12738 will be done in Aug(#2077)

---

main/plugins/org.talend.hadoop.distribution.spl30x/plugin.xml

fix(TBD-12314): spl30x - Job fails when tS3Configuration component is used with Assume Role (#2072)

---

main/plugins/org.talend.hadoop.distribution.hdinsight360/src/main/java/org/talend/hadoop/distribution/hdinsight360/HDInsight36Distribution.java

feat(TBD-12576): added 'deprecated' to distribution name

---

main/plugins/org.talend.hadoop.distribution.hdinsight360/src/main/java/org/talend/hadoop/distribution/hdinsight360/HDInsight36Distribution.java

feat(TBD-12576): added 'deprecated' to distribution name (#2061)

---

main/plugins/org.talend.hadoop.distribution.spl30x/plugin.xml

fix(TBD-12314): spl30x - Job fails when tS3Configuration component is used with Assume Role

---

main/plugins/org.talend.hadoop.distribution.spl30x/plugin.xml

fix(TBD-12704):upgrade commons-lang3 to 3.10

---

main/plugins/org.talend.hadoop.distribution.spl30x/plugin.xml

fix(TBD-12704):upgrade commons-lang3 to 3.10 (#2080)

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_3_1_4_12_1.json
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/hdp/DynamicHDPDistributionsGroup.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/AbstractDynamicDistributionTemplate.java

fix(TBD-12577): added 'Deprecated' to dynamic distro and wizard

---

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_3_1_4_12_1.json
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/hdp/DynamicHDPDistributionsGroup.java
main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/AbstractDynamicDistributionTemplate.java

fix(TBD-12577): added 'Deprecated' to dynamic distro and wizard (#2074)

---

main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json

fix(TBD-12827):Can't create dynamic CDP distribution

---

main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json

* fix(TBD-12827):Can't create dynamic CDP distribution
* fix(TBD-12827):Can't create dynamic CDP distribution
* fix(TBD-12827):Can't create dynamic CDP distribution

fix(TBD-12827):Can't create dynamic CDP distribution (#2096)

---

main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/KnoxInfoForm.java
main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/context/handler/HadoopClusterContextHandler.java
main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/dnd/HDFSDragAndDropHandler.java

fix(TBD-12767):[BUG] The configurations can be updated after Export a… (#2094)

---

main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/manager/HadoopOperationManager.java

fix(TBD-12829):Can't open subwindow for tHDFSXXX on DI job

---

main/plugins/org.talend.designer.hdfsbrowse/src/org/talend/designer/hdfsbrowse/manager/HadoopOperationManager.java

fix(TBD-12829):Can't open subwindow for tHDFSXXX on DI job (#2101)

---

main/plugins/org.talend.spark.distribution.spark24x/plugin.xml
main/plugins/org.talend.spark.distribution.spark30x/plugin.xml
main/plugins/org.talend.spark.distribution.spark31x/plugin.xml

fix(TBD-12973): add avro-mapred for TDM

---

main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json

fix(TBD-12519):Issues with dynamic CDP 7.1

---

continuous-integration/Jenkinsfile

chore(TBD-13489):Auto patch build fails if patch name arg contains /

---

README.md
main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh550/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh570/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh580/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh580spark2/plugin.xml
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH5_13_0.json
main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
main/plugins/org.talend.hadoop.distribution.hdp250/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml
main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdp2xx/Hortonworks_HDP_2_6_0_3_8.json
main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdp2xx/hdp2xxTemplate.json

security patch, remove spring dependencies
Delete spring unused dependency

feat(TBD-13785): security patch, remove spring dependencies

---

main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml

fix(TBD-13422): [Random] NoClassDefFoundError exception when I run a spark job with EMR515

---

main/plugins/org.talend.spark.distribution.spark32x/plugin.xml
main/plugins/org.talend.spark.distribution.spark33x/plugin.xml

fix(TBD-15877): Runtime exception on Spark job with Delimited components using tAzureFSConfiguration

---

main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_java.xml

https://jira.talendforge.org/browse/TDI-50380
https://jira.talendforge.org/browse/TDI-50380

fix(TDI-50380): avro:[1.8.1,1.8.2,1.11.2]| CVE-2023-39410

---

main/plugins/org.talend.spark.distribution.spark24x/plugin.xml

fix(TBD-15889): Error using tDataMasking

---

main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/dnd/HDFSDragAndDropHandler.java

fix(TBD-15703): support repository item switch about Standalone

---

main/plugins/org.talend.designer.components.bigdata/components/tKafkaConnection/tKafkaConnection_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_java.xml
main/plugins/org.talend.designer.components.bigdata/plugin.xml

https://jira.talendforge.org/browse/TDI-50450

fix(TDI-50450): CVE upgrade snappy-java to 1.1.10.5

---

main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/tCassandraOutputBulk_java.xml
main/plugins/org.talend.designer.components.bigdata/plugin.xml

fix(TDI-50450):cve upgrade snappy-java to 1.1.10.5

---

main/plugins/org.talend.repository.nosql/plugin.xml

https://jira.talendforge.org/browse/TUP-41010

feat(TUP-41010):Remove deprecated version 3 of Cassandra

---

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/dynamic/form/DynamicDistributionPreferenceForm.java

fix(TUP-41413) set application mode
