main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/service/HadoopClusterService.java
TBD-3202: [6.1.1] Hive properties dont get submitted correctly when
re-using context
TBD-3212: hadoop cluster:hadoop property is added double quotes when
drag hdfs schema to a standard job
=> Fixed the bugs:

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/model/DistributionBean.java
Don't know it is ok for my fix (so simply like this)
Because related to CDH510MR2Distribution, will get the showif  value "(((false)))" and caused the problem.
https://github.com/Talend/tbd-studio-se/blob/bugfix/6.2/TBD-3338/main/plugins/org.talend.hadoop.distribution.cdh510mr2/src/main/java/org/talend/hadoop/distribution/cdh510mr2/CDH510MR2Distribution.java#L61
but for others are null, and will add null always. 
https://github.com/Talend/tdi-studio-se/blob/b5bca732a4a20862a3fc023cbe84b08d2f11a7a7/main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EmfComponent.java#L1631
=> TBD-3338: change back like before to enable add null for conditions

main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml
The `hive-exec` dependency is wrongly declared for Dataproc 1.1 distribution, causing all Spark jobs including a Hive component to fail.
The `hive-exec` dependency is now correctly declared.
=> fix(TBD-4803): correct hive-exec dependency declaration for Dataproc 1.1

main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml
The `talend-bigdata-launcher` library currently used in Dataproc 1.1 is subject to this issue : https://jira.talendforge.org/browse/TBD-4824
`talend-bigdata-launcher` has been updated to fix the above issue. Dataproc 1.1 now includes the latest `talend-bigdata-launcher` version.
The new `talend-bigdata-launcher` has not been uploaded to the Talend-update Nexus yet.
=> fix(TBD-4824): upgrade talend-bigdata-launcher version for Dataproc 1.1

main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/hiveUtil.javajet
There's no double quote on column's comment. As a result, there'll be a compile error.
Add double quotes for each column's comment, then the compile errors disappear.
=> fix(TBD-4805): add double quotes for each column's comment

main/plugins/org.talend.designer.components.bigdata/components/tPigStoreResult/tPigStoreResult_java.xml
during build job.
The hive-metastore-1.2.1.2.3.2.0-2950.jar will be renamed during build job.Intercept
cased by the intercept jar name in the tPigStoreResult xml
=> fix TUP-17486:The hive-metastore-1.2.1.2.3.2.0-2950.jar will be renamed during build job.

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/context/handler/HadoopClusterContextHandler.java, test/plugins/org.talend.repository.hadoopcluster.test/src/main/java/org/talend/repository/hadoopcluster/ui/context/handler/HadoopClusterContextHandlerTest.java
=> TUP-17227: WHen reuse context group for hadoop cluster,miss hadoop properties parameter

main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/hiveUtil.javajet
varchar2 column type not supported in hive.
Replace varchar2 with varchar.
=> fix(TBD-4805): change varchar2 with varchar

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/GoogleDataprocInfoForm.java
credentials file.
=>Not have the file select browse button for Path to Google Credentials file
=>Add a button on Google Cloud Dataproc wizard to browse Google credentials file
=> feat TUP-17522:Add a button on Google Cloud Dataproc wizard to browse Google credentials file

main/plugins/org.talend.hadoop.distribution.dataproc11/src/main/java/org/talend/hadoop/distribution/dataproc11/Dataproc11Distribution.java, test/plugins/org.talend.hadoop.distribution.dataproc11.test/src/org/talend/hadoop/distribution/dataproc11/test/Dataproc11DistributionTest.java
fix(TUP-17567): there should no "Create Oozie" context menu on Google Hadoop Cluster
https://jira.talendforge.org/browse/TUP-17567
=> fix(TUP-17567): there should no "Create Oozie" context menu on Google Hadoop Cluster

main/plugins/org.talend.hadoop.distribution.cdh580spark2/plugin.xml, main/plugins/org.talend.hadoop.distribution.cdh580spark2/src/main/java/org/talend/hadoop/distribution/cdh580spark2/CDH580Spark2Distribution.java, main/plugins/org.talend.hadoop.distribution.hdp250/plugin.xml, main/plugins/org.talend.hadoop.distribution.hdp250/src/org/talend/hadoop/distribution/hdp250/HDP250Distribution.java, main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java, main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkStreamingComponent.java, test/plugins/org.talend.hadoop.distribution.cdh580spark2.test/src/org/talend/hadoop/distribution/cdh580spark2/test/CDH580Spark2DistributionTest.java, test/plugins/org.talend.hadoop.distribution.hdp250.test/src/org/talend/hadoop/distribution/hdp250/test/HDP250DistributionTest.java
- There is no support of kerberized Kafka in Spark Streaming for any distribution.
- CDH 5.8 Spark 2 was integrated with the wrong Kafka artifacts, preventing Kerberos and SSL to work.
- The distribution API has been updated to handle kerberized Kafka for some Spark 1.6 distributions : only HDP has backported the new Kafka consumer API in their spark-streaming-kafka connector for Spark 1.6. This has been validated against HDP 2.5 (it might work also with HDP 2.4 but did not invest the time to investigate this at the time of writing).
- CDH 5.8 Spark 2 now integrates the right Kafka artifacts
**Other information**: 
This PR should …
=> feat(TBD-4866): fix CDH 5.8 Spark 2.0 integration regarding Kafka and update distribution API

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/conf/RetrieveLocalConfsService.java
cluster is created throuth retrieve from jobserver
https://jira.talendforge.org/browse/TUP-17545
=> fix(TUP-17545):Hadoop properties filter is not token effect when hadoop

main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/dnd/HCatalogDragAndDropHandler.java
HCatalog schema to job
The HCatalog components show when drag HDInsight HCatalog schema to job
The HCatalog components should not show when drag HDInsight HCatalog schema to job
=> fix TUP-17310:The HCatalog components should not show when drag HDInsight

main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml
Compile error when using tAvroOutput in HDI 36 Spark job.
No compile error when using tAvroOutput in HDI 36 Spark job.
=> fix(TBD-5148): Add jackson-core-asl dependency in HDInsight 3.6 distribution

main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml
Compile error when using tNormalize component in Spark job with HDI 36.
Add commons-logging dependency to HDI_36_COMMON_LIBRARIES group. No compile error.
=> fix(TBD-5149): Add commons-logging dependency to HDI_36_COMMON_LIBRARIES group

main/plugins/org.talend.designer.components.bigdata/components/tHBaseConnection/tHBaseConnection_java.xml, main/plugins/org.talend.hadoop.distribution.cdh580/plugin.xml
NoClassDefFoundError exception occured. Netty-all dependency is missing.
Add netty-all dependency on tHBaseConnection component with CDH580.
=> fix(TBD-4883): Add netty-all dependency on tHBaseConnection CDH580

main/plugins/org.talend.hadoop.distribution.cdh570/plugin.xml
No download link shown regarding `jackson-annotations-2.3.0` while using CDH 5.7 Spark. This is caused by a missing dependency declaration in the distribution `plugin.xml` file.  
`jackson-annotations-2.3.0` is now properly declared, and already present on Nexus. The jar download works.
=> fix(TBD-4869): add missing dependency declaration in CDH 5.7

main/plugins/org.talend.hadoop.distribution.altus10/plugin.xml, main/plugins/org.talend.hadoop.distribution.altus10/src/main/java/org/talend/hadoop/distribution/altus10/Altus10Distribution.java, main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/constants/cdh/altus/IClouderaAltusDistribution.java
Altus use a bad version of the talend-bigdata-launcher
The version of the talend-bigdata-launcher is now correct.
=> feat(TBD-5171): Change jar version to match release ; small UI tweak.

main/plugins/org.talend.hadoop.distribution.dataproc11/plugin.xml
`tGoogleDataprocManage` shares its `talend-bigdata-launcher` module group with the Dataproc 1.1 distribution.
To fix https://jira.talendforge.org/browse/TBD-5244, changes were made on the `talend-bigdata-launcher`. 
Since we are really close to the 6.4.1 code freeze, a dedicated module group has been created for `tGoogleDataprocManage` not to take any chances to cause regressions on Dataproc 1.1 MapReduce and Spark. 
This new module group (with the updated `talend-bigdata-launcher`) is only used by `tGoogleDataprocManage`. 
This PR must be merged alongside of https://github.com/Talend/tdi-studio-se/pull/1388
=> fix(TBD-5244): create dedicated module group for tGoogleDataprocManage

main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml
See https://jira.talendforge.org/browse/TBD-5208. This is caused by a wrong version of the `breeze` dependency in CDH 5.10 distribution.
The `breeze` dependencies have been upgraded to 0.12, accordingly with https://github.com/cloudera/spark/blob/spark2-2.1.0-cloudera1/pom.xml#L704.
The relevant jars are already on Nexus.
=> fix(TBD-5208): add correct breeze dependencies in CDH 5.10 Spark 2

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_java.xml
query type
CosmosDB doesn't support AGGREGATION_QUERY
Remove AGGREGATION_QUERY for tCosmosDBInput and hide query type.
=> fix(TDI-39018):remove AGGREGATION_QUERY for tCosmosDBInput and hide

main/plugins/org.talend.designer.components.bigdata/components/tCassandraConnection/tCassandraConnection_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tCassandraInput/tCassandraInput_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutput/tCassandraOutput_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tCassandraRow/tCassandraRow_java.xml
Guava conflict between hdfs component and cassandra component
Shade guava in cassandra-driver-core to solve this issue
build cassandra-driver-core-3.0.0-shaded by https://github.com/Talend/java-driver/tree/v3.0-patched-20170614
build talend-cassandra-1.2.jar by https://github.com/Talend/tdi-studio-ee/pull/466
=> fix tbd 4930 guava conflict b62

main/plugins/org.talend.designer.components.bigdata/components/tCassandraConnection/tCassandraConnection_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tCassandraInput/tCassandraInput_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutput/tCassandraOutput_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tCassandraRow/tCassandraRow_java.xml
Guava conflict between hdfs component and cassandra component
Shade guava in cassandra-driver-core to solve this issue
build cassandra-driver-core-3.0.0-shaded by https://github.com/Talend/java-driver/tree/v3.0-patched-20170614
build talend-cassandra-1.2.jar by Talend/tdi-studio-ee#466
=> fix tbd 4930 b63

main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/HCatalogForm.java, main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/ui/HDFSForm.java, main/plugins/org.talend.repository.hdfs/src/org/talend/repository/hdfs/util/HDFSModelUtil.java
*when have many context groups within Hive, Hbase, Hcate or HDFS, open
their wizard will not pop up select-context dialog now. 
*dialog will not appear when check service also.
https://jira.talendforge.org/browse/TUP-18019
=> fix(TUP-18019)context group dialog popup manytimes when check service

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_begin.javajet, main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_main.javajet
https://jira.talendforge.org/browse/TDI-39013
* Use of the output schema to get correct columns name and metadata (key, db column name ...) instead of the incomming schema
* Ignore null and empty values in the incoming data. (dynamo db don't accept that)
* Add LONG conversion to Scalar Numeric Type of dynamoDB
=> fix(TDI-39013): fix dynamoDB insertion error

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java
*add sashform and scrolledComposite for hadoop cluster wizard.
https://jira.talendforge.org/browse/TUP-17718
=> fix(TUP-17718)Certain options cut off due to resolution size

main/plugins/org.talend.repository.maprdbprovider/src/main/java/org/talend/repository/maprdbprovider/provider/MapRDBMetadataProvider.java, pom.xml, test/features/org.talend.bigdata.se.test.feature/feature.xml, test/plugins/org.talend.repository.maprdbprovider.test/.classpath, test/plugins/org.talend.repository.maprdbprovider.test/.project, test/plugins/org.talend.repository.maprdbprovider.test/META-INF/MANIFEST.MF, test/plugins/org.talend.repository.maprdbprovider.test/build.properties, test/plugins/org.talend.repository.maprdbprovider.test/pom.xml, test/plugins/org.talend.repository.maprdbprovider.test/src/org/talend/repository/maprdbprovider/test/MapRDBMetadataProviderTest.java
families in MapRDB
- [* ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ *] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [* ] The new code does not introduce new technical issues
metadata Columns have the names
when db Columns have the names, we will reset the metadata Column name,to make sure metadata Columns  do not have the names
If not please remove this …
=> fix(TUP-18159):Compile error when same column names in different column

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_begin.javajet, main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_main.javajet
https://jira.talendforge.org/browse/TDI-39056
Add Support of Talend Types:
Date type are formatted to String using the user pattern and stored to dynamodb as a String (the supported dynamodb format for date)
Nullable columns are submited to dynamodb as Null(DynamoDB type)
If column is of type String or byte[] and is nullable. If the column value is empty we also submit it as Null (DynamoDB type).
If the column are non Nullable and the column value are Null (or Empty in case of String, byte[] type) we ignore them in the insertion.
DynamoDB expect Attribute values to not be null. String and Binary type attributes must have lengths …
=> Tdi 39056 extend types support handle nullable in DynamoDBOutput

main/plugins/org.talend.hadoop.distribution.emr550/plugin.xml
See https://jira.talendforge.org/browse/TBD-5390. EMR 5.5 mistakenly imports Avro 1.7.4 in its HDFS module group instead of Avro 1.7.7, causing large Avro schemas to be unusable.
Only the HDFS module group was wrong regarding this.
EMR 5.5 now consistently imports Avro 1.7.7 for all module groups.
=> fix(TBD-5390): ensure to use Avro 1.7.7 instead of 1.7.4 with EMR 5.5 HDFS

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_begin.javajet
https://jira.talendforge.org/browse/TDI-39221
DynamoDB only have the data type of
{String number binary}
so I will change the date type to String, as we insert Date as String in tDynamoDBOutput.
=> fix(TDI-39221):tackle tDynamoDBInput ClassCastException

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml
Cherry-picked commit back into maintenance/6.4 -- will fix mergeability of branches later.
* TBD5416 Update netty-all version to 4.0.42
* TBD5416 Revert unnecessary changes to module groups not related to Spark
=> TBD-5416 Update netty-all version to 4.0.42 (#424)

main/plugins/org.talend.designer.components.bigdata/components/tELTHiveMap/tELTHiveMap_main.javajet
tETLHiveMap generates compilation error if contains carriage returns in the SQL
https://jira.talendforge.org/browse/TBD-5540
tETLHiveMap generates correct code if contains carriage returns in the SQL
=> fix(TBD-5540/components): fixed (tETLHiveMap cannot have carriage returns in the syntax)

main/plugins/org.talend.designer.components.bigdata/components/tELTHiveOutput/tELTHiveOutput_main.javajet, main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_main.javajet, main/plugins/org.talend.designer.components.bigdata/components/tHiveInput/tHiveInput_begin.javajet, main/plugins/org.talend.designer.components.bigdata/components/tHiveLoad/tHiveLoad_main.javajet
This PR totally depends on https://github.com/Talend/tdi-studio-se/pull/1646.
Be able to get hive query name (to monitor it on yarn or Tez) while running Hive job including tHiveInput, tHiveLoad, tHiveCreateTable or tELTHiveOutput.
=> feat(TBD-4197): set hive query name for tracking

main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_javaapi.javajet
Vertica JDBC driver is not loaded when trying to use tSqoopImport component with vertica driver.
https://jira.talendforge.org/browse/TBD-5578
Vertica JDBC driver is loaded succesfully
=> fix(TBD-5578/components): tImportSqoop fails Against Vertica JDBC driver

main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/0.10.0.x/tKafkaCreateTopic_begin_0.10.0.x.javajet, main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/0.8.2.x/tKafkaCreateTopic_begin_0.8.2.x.javajet, main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/0.9.0.x/tKafkaCreateTopic_begin_0.9.0.x.javajet
[TBD-5803](https://jira.talendforge.org/browse/TBD-5803)
retention time can only be a number, this prevent a context variable from being used
retention time can be a number or a string.
=> Cannot set tkafkacreatetopic component retention time with context variable

main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml
fix(TUP-18774): retrieve schema from HDFS ( Encrypted zone) remains on Pending
https://jira.talendforge.org/browse/TUP-18774
=> fix(TUP-18774): retrieve schema from HDFS ( Encrypted zone) remains on Pending

main/plugins/org.talend.hadoop.distribution.cdh580/plugin.xml
Missing dependency which was fixed in 6.4
Cherry-pick the 6.4 fix to 6.3
=> fix(TBD-4117): Add netty-all dep to HBASE-LIB-CDH_5_8 module group

main/plugins/org.talend.hadoop.distribution.emr550/plugin.xml
Error message on job execution with tLogisticRegressionModel: 
Exception in thread "main" java.lang.NoSuchMethodError: breeze.linalg.DenseVector$.space_Double()Lbreeze/math/MutableFiniteCoordinateField;
Fixed
=> fix(TBD-5297): change breeze jar version on emr 5.5

main/features/org.talend.rcp.branding.tos.bigdata.feature/feature.xml
onboarding is available for every products, even oems.
They should be on talend products only
Set onboarding in the talend product feature directly
=> fix(TUP-19187) Set onboarding for talend products only

main/plugins/org.talend.hadoop.distribution.altus10/plugin.xml
Upgrade to 1.6.1 to get the one already uploaded to Nexus
Won't break anything according to changelog : https://github.com/awslabs/amazon-kinesis-client
=> fix(TBD-6274) : Upgrade kinesis client to 1.6.1 for Altus

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_main.javajet
https://jira.talendforge.org/browse/TDI-39966
If an empty String "" is given to a JSON db type field, then empty json "{}" is sent to dynamodb.
=> fix(TDI-39966) : DynamoDB empty string is empty json

main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/hiveUtil.javajet
tHiveCreateTable component don't handle null column in the schema
https://jira.talendforge.org/browse/TBD-5625
nullable columns are handled now
=> TBD-5625: accept nullable column in tHiveCreateTable with Avro Schema

main/plugins/org.talend.hadoop.distribution.emr450/plugin.xml
Redshift components are not working on EMR 4.5/4.6
Redshift components are working on EMR 4.5/4.6
=> fix(TBD-4424):Redshift components need avro 1.7.6+

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/DynamicDistributionManager.java
Dyanmic: when Import two dynamic configuration, create hadoop cluster then select second one as distribution, cann't check success.
Dyanmic: when Import two dynamic configuration, create hadoop cluster then select second one as distribution, cann check success now.
=> fix(TUP-19329):Dyanmic: when Import two dynamic configuration, second one cann't check success.

main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java
Contextualize Custom Hadoop Connection - Unable to remove JobTrackerUri as field option
Can use the current  Resource Manager in field as context if the custom use yarn mode
=> fix(TUP-19529):Contextualize Custom Hadoop Connection - Unable to remove JobTrackerUri as field option.

main/plugins/org.talend.designer.components.bigdata/components/tSqoopExport/tSqoopExport_javaapi.javajet, main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_javaapi.javajet, main/plugins/org.talend.designer.components.bigdata/components/tSqoopImportAllTables/tSqoopImportAllTables_javaapi.javajet, main/plugins/org.talend.designer.components.bigdata/components/tSqoopMerge/tSqoopMerge_javaapi.javajet
=> fix(TBD-6671): make Sqoop use driver class name when there is no built-in connection mananger

main/plugins/org.talend.designer.components.bigdata/components/tImpalaLoad/tImpalaLoad_main.javajet
This variables are used by Hive on Qubole and Impala reuses some Hive code.
=> fix: Add var declarations needed by Hive on Qubole

main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh5x/CDH5xDistributionTemplate.java, main/plugins/org.talend.hadoop.distribution.databricks/src/main/java/org/talend/hadoop/distribution/databricks/DatabricksDistribution.java, main/plugins/org.talend.hadoop.distribution.qubole/src/main/java/org/talend/hadoop/distribution/qubole/QuboleDistribution.java
Wrong AWS API used for some distributions
Databricks, Qubole, CDH dynamic distributions does not support slashes in AWS S3 URIs and fallback to anonymous authentication if so.
All these distributions have support enabled for slashes.
=> fix(TBD-8075): Addition of slash support for AWS

main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml
Nexus jar for spark-mllib-local_2.11-2.2.0.cloudera1 and is conflicting with spark-mllib jar. Also it is different from official jar.
Use official jar to replace the faulty jar which remove the conflict.
=> fix(TBD-7961): Use Cloudera official jar for mllib-local on CDH 5.12

main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/DynamicDistributionManager.java, main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/helper/DistributionsManager.java
fix(TUP-21176): Reload Dynamic Distribution jars in a right place 
https://jira.talendforge.org/browse/TUP-21176
=> fix(TUP-21176): Reload Dynamic Distribution jars in a right place (#942)

main/plugins/org.talend.hadoop.distribution.emr5150/src/main/java/org/talend/hadoop/distribution/emr5150/EMR5150Distribution.java
=> fix(TBD-8145): Use newer s3a key properties for EMR 5.15 (#946)

main/plugins/org.talend.repository.nosql/src/messages.properties, main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/handler/cassandra/CassandraMetadataHandler.java, main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/handler/cassandra/CassandraOldVersionMetadataHandler.java, main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/mongodb/MongoDBConnectionUtil.java, main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/neo4j/Neo4jConnectionUtil.java, main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/common/AbstractNoSQLConnForm.java, test/plugins/org.talend.repository.nosql.test/src/org/talend/repository/nosql/db/util/neo4j/Neo4jConnectionUtilTest.java, test/plugins/org.talend.repository.nosql.test/src/org/talend/repository/nosql/db/util/neo4j/Neo4jMetadataProviderTest.java
already checked Neo4j 2.1.x connection
https://jira.talendforge.org/browse/TUP-15692
=> fix(TUP-15692)Check fail for Second Neo4j 2.2.x connection when I

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_main_below_3_5.javajet
=> fix(TDI-41553): Fix compile error when old mongo version used

main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_begin.javajet
* Add support for JSON String in tDynamoDBInput
JSON Strings are represented as Key=Value pairs
JSON String is presented correctly
=> feat(TDI-42173): JSON String in tDynamoDBInput

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml
https://jira.talendforge.org/browse/TDI-42689
BigDecimal is used instead of float & double to avoid lose of decimal precision.
Upgrade json-lib from 2.4.1-talend to -2.4.2-talend to have the fix.
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
=> fix(TDI-42689) : Uprade js-lib to 2.4.2-talend

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml
* fix(TDI-37801): Update json-lib version in components
https://jira.talendforge.org/browse/TDI-37801
Backport to 7.2
=> fix(TDI-37801): tWriteJSONField null values (Backport to 7.2)

main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchOutput/tNeo4jBatchOutput_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchOutputRelationship/tNeo4jBatchOutputRelationship_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchSchema/tNeo4jBatchSchema_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tNeo4jImportTool/tNeo4jImportTool_java.xml
Commons-compress library from Apache has multiple different version in components.
Align common-compress library version to newest available - 1.19 (https://commons.apache.org/proper/commons-compress/)
=> fix(TDI-42834): upgrade commons-compress library to latest version

main/plugins/org.talend.repository.hadoopcluster.configurator/pom.xml
add missing okkio dependency
package com.squareup.okio is a transitive dependency of cloudera manager API.
It miss in the filter for copy-dependencies phase.
added missing groupId com.squareup.okio
remove non needed org.hamcrest groupId as it is a test scope dependencies
=> fix(TBD-9421): add missing okkio dependency

Jenkinsfile, tools/commit-check.py, tools/sanity-check.py
Description
There is a consensus in Talend about what a commit message format.
ON TBD repositories, there is no tools to ensure this format. 
As a consequence, this format is not followed everytime and history
is a little bit hard to read/understand.
Add a simple script that check the format.
**Ticket is** TBD-9561
=> chore(TBD-9561): add sanity check on commit message

main/plugins/org.talend.repository.hbaseprovider/src/org/talend/repository/hbaseprovider/provider/HBaseMetadataProvider.java
TBD-9793
We can not retrieve anymore tables and columns from the schema retreiver.
This is due to some API in CDH 5.13 that is not the standard one (still got some old methods names).
Try the standard one, in case of NoSuchMethodError, try the old one. This allow the retreiver to be able to work with CDH 5.13
=> fix(TBD-9793): Failed to retrieve hbase schema for CDH5.13 and HDP2.6

main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
Fix the maven uri and the version of a jar for Google Dataproc 1.4
=> fix(TBD-9807): missing jar for Dataproc 1.4

main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml, main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml
https://jira.talendforge.org/browse/TDI-43610
A decimal value in a json with non-significant 0, keep at least one non-significant 0 to keep the double type "10.0000" -> "10.0"
=> fix(TDI-43610): jsonutil bump version to 2.4.5-talend

test/plugins/org.talend.hadoop.distribution.hdinsight340.test/src/org/talend/hadoop/distribution/hdinsight340/test/HDInsight34ClassLoaderTest.java
The junit failed, just remove it, since it seems that no one cares the
junit and it will be removed from deprecated sooner or later
=> chore[TBD-9558]: remove classloader junit of HDInsight3.4

main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json, main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json
forked hive repository from Cloudera
created a shaded jar for hive-exec (cdh6.1)
exclude hive-exec from dynamic distro
forced the usage of the shaded version
created a new built-in
=> fix(TBD-10093): XXX illegal pattern CDH61

main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_2_6_0_3_8.json, main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp2xxTemplate.json
- Added parquet-avro 1.4.1 needed by org.kitesdk:kite-data-core:jar:1.0.0
- Regenerated HDP 2.6 built-in
=> fix(TBD-9956):Sqoop issue with Java API/parquet format/HDP 2.6

test/plugins/org.talend.hadoop.distribution.hdinsight340.test/src/org/talend/hadoop/distribution/hdinsight340/test/HDInsight34ClassLoaderTest.java
The junit failed, just remove it, since it seems that no one cares the
junit and it will be removed from deprecated sooner or later
=> chore[TUP-26355]: remove classloader junit of HDInsight3.4 (#1281)

main/plugins/org.talend.hadoop.distribution.hdinsight340/plugin.xml, main/plugins/org.talend.hadoop.distribution.hdinsight360/plugin.xml, main/plugins/org.talend.hadoop.distribution.hdinsight360/src/main/java/org/talend/hadoop/distribution/hdinsight360/HDInsight36Distribution.java, main/plugins/org.talend.hadoop.distribution.hdinsight400/plugin.xml, main/plugins/org.talend.hadoop.distribution.hdinsight400/src/main/java/org/talend/hadoop/distribution/hdinsight400/HDInsight40Distribution.java, main/plugins/org.talend.hadoop.distribution.hdinsight400/src/main/java/org/talend/hadoop/distribution/hdinsight400/modulegroup/HDInsight40HiveOnSparkModuleGroup.java
TBD-10748
Fix several dependencies issues:
- fix non working dependencies for hive-spark on HDI 4.0 and 3.6
- fix bad constructor for bigdata-launcher by updated dependencies to 2.0.8 on HDI 3.4 and 3.6
=> fix(TBD-10748): Compiler error when spark job use tHiveInput component

main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
https://jira.talendforge.org/browse/TDI-44039
https://github.com/Talend/bigdata-launcher/pull/11
Studio use old version of talend-bigdata-launcher-dataproc lib that does not support internalIpOnly for cluster configuration
Update library to the latest version
=> feat(TDI-44039): update version of dataproc

main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main.javajet, main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_3_5_X.javajet, main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_below_3_5.javajet
https://jira.talendforge.org/browse/TDI-44614
Data of date type with same JSON path will process only once.
If dates with same JSON path have same pattern exception will be thrown.
Backport
=> fix(TDI-44614): tMongoDBOutput dates cast problem

main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml, main/plugins/org.talend.hadoop.distribution.dataproc14/src/main/java/org/talend/hadoop/distribution/dataproc14/Dataproc14Distribution.java, main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java, main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java, main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/helper/DistributionsManager.java
- Updated dependencies to Spark 2.4.7 and Hive 2.3.7 according to https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-1.4
- set metastore jars path to point where driver running on master node can find them
=> fix(TBD-11675):DataProc Spark Hive Job fails with error java.lang.NoSuchMethodException

main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/HCatalogSchemaForm.java
Feat:TUP-30377 Move the "Allow specific characters (UTF8,...)" preference setting to project setting.
https://jira.talendforge.org/browse/TUP-30377
=> fix(TUP-30377):TUP-30377 Move the "Allow specific characters (UTF8,...)" preference setting to project setting.
